"""PowerShell tool that executes commands via the system PowerShell executable."""

import asyncio
import pybase64 as base64
import contextlib
import functools
import os
from pathlib import Path
import regex as re
import shutil
import subprocess
import sys
from typing import TYPE_CHECKING, Literal

import kimi_cli
from kimi_agent_sdk import CallableTool2, ToolError, ToolOk, ToolReturnValue
from pydantic import BaseModel, Field, model_validator
from kimi_cli.session import Session
from kimi_cli.tools import SkipThisTool
from kimi_cli.tools.utils import load_desc
from kimi_cli.tools.display import ShellDisplayBlock
from kimix.tools.file.bash import bash_tool as _bash_tool
from kimix.tools.file.bash.proccess_pwsh import pwsh_transform
from kimix.tools.common import (
    _build_session_output_block,
    _env_with_rg_bin_path,
    _extract_export_path,
    _interactive_scope_text,
    _maybe_export_output_async,
    _maybe_rewrite_shell_command_with_rtk,
    _summarize_long_output_async,
    _token_filter_output,
    ProcessTask,
)

if TYPE_CHECKING:
    from kimi_agent_sdk import CallableTool2 as _CallableTool2

# Console initialization prepended to every PowerShell command. Sets UTF-8
# output encoding and treats Ctrl+C as regular input so that console control
# signals generated by or sent to the PowerShell subprocess do not propagate
# back and raise KeyboardInterrupt in the parent Python process.
_PWSH_CONSOLE_INIT = (
    "[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;"
    "$OutputEncoding=[System.Text.Encoding]::UTF8;"
    "try{[Console]::TreatControlCAsInput=$true}catch{};"
)

def _print_warning(message: str) -> None:
    """Print a yellow WARNING message to stderr."""
    yellow = "\033[33m"
    reset = "\033[0m"
    print(f"{yellow}WARNING: {message}{reset}", file=sys.stderr, flush=True)

def _pwsh_major_version(path: str) -> int | None:
    """Return the major version reported by a PowerShell executable, or None."""
    try:
        output = subprocess.check_output(
            [path, "-NoP", "-NonI", "-C", "$PSVersionTable.PSVersion.Major"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=3,
        ).strip()
        return int(output)
    except (OSError, subprocess.TimeoutExpired, ValueError):
        return None


def _is_windows_apps_stub(path: str) -> bool:
    """Return True if *path* points into the WindowsApps directory (Store stub)."""
    return "WindowsApps" in os.path.normpath(path).split(os.sep)


def _where_candidates(name: str) -> list[str]:
    """Return candidate paths reported by ``where.exe <name>``, excluding WindowsApps stubs."""
    try:
        result = subprocess.run(
            ["where.exe", name],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []
    if result.returncode != 0:
        return []
    return [
        line.strip() for line in result.stdout.splitlines()
        if line.strip() and not _is_windows_apps_stub(line.strip())
    ]


def _common_fixed_pwsh_paths() -> list[str]:
    """Return well-known PowerShell 7 installation paths for the current platform.

    On Windows these are checked *before* ``where.exe`` results so that the
    genuine MSI install is preferred over Store execution aliases.
    """
    if sys.platform == "win32":
        return [
            r"C:\Program Files\PowerShell\7\pwsh.exe",
            r"C:\Program Files (x86)\PowerShell\7\pwsh.exe",
        ]
    return [
        "/opt/microsoft/powershell/7/pwsh",
        "/usr/local/bin/pwsh",
        "/usr/bin/pwsh",
    ]


@functools.lru_cache(maxsize=1)
def find_pwsh() -> str | None:
    """Find PowerShell 7.x on the current platform.

    Resolution order:
      1. Common fixed installation paths (MSI install on Windows).
      2. ``pwsh`` / ``pwsh.exe`` on PATH (via ``shutil.which``).
      3. ``where.exe pwsh.exe`` on Windows (WindowsApps stubs filtered out).

    Returns the absolute path to a PowerShell 7+ executable, or ``None`` if
    only Windows PowerShell 5.1 (or no PowerShell) is available.
    """
    candidates: list[str] = []

    # 1. Fixed common install locations (checked first so MSI install is
    #    preferred over Store execution aliases on Windows).
    candidates.extend(_common_fixed_pwsh_paths())

    # 2. PATH
    if sys.platform == "win32":
        names = ["pwsh.exe", "pwsh"]
    else:
        names = ["pwsh"]
    for name in names:
        resolved = shutil.which(name)
        if resolved:
            candidates.append(resolved)

    # 3. where.exe (Windows only) — WindowsApps stubs already filtered
    if sys.platform == "win32":
        for name in names:
            candidates.extend(_where_candidates(name))

    seen: set[str] = set()
    for candidate in candidates:
        candidate = shutil.which(candidate) or candidate
        if not os.path.exists(candidate):
            continue
        norm = os.path.normcase(os.path.abspath(candidate))
        if norm in seen:
            continue
        seen.add(norm)
        major = _pwsh_major_version(candidate)
        if major is not None and major >= 7:
            return candidate

    return None


class PowershellParams(BaseModel):
    """Parameters for the Powershell tool — execute a PowerShell command."""

    model_config = {"populate_by_name": True}

    cmd: str = Field(
        default="",
        alias="command",  # LLM can use "command" instead of "cmd"
        description="PowerShell command or input text for an existing session. Accepts `cmd` or `command`."
    )
    mode: Literal["execute", "send"] = Field(
        default="execute",
        description=(
            "'execute': Run the PowerShell command. "
            "'send': Send command as stdin text to an existing session identified by `task_id`."
        ),
    )
    timeout: int = Field(
        default=30,
        ge=1,
        le=900,
        description="Timeout in seconds (1-900)."
    )
    interactive: bool = Field(
        default=False,
        description=(
            "Run PowerShell interactively. "
            "The process stays alive and accepts further input via task_id. "
            "Returns a task_id immediately; use TaskOutput to read output."
        ),
    )
    task_id: str | None = Field(
        default=None,
        description=(
            "Existing session/task ID to continue. When provided, 'cmd' is sent to the "
            "process stdin instead of being executed."
        ),
    )
    wait_for_pattern: str | None = Field(
        default=None,
        description=(
            "Optional regex pattern. After starting or sending input, the tool blocks up "
            "to 'timeout' seconds until the pattern appears in output."
        ),
    )
    max_lines: int | None = Field(
        default=None,
        ge=3,
        description="Max lines to return via head+tail fold. <N> head lines + <N> tail lines kept; middle collapsed. None = unlimited.",
    )
    deduplicate_output: bool = Field(
        default=True,
        alias="token_kill",  # backward compat
        description="Deduplicate repeated output lines from known commands (git, npm, etc.). "
                    "Set to False to see raw, unfiltered output.",
    )

    @model_validator(mode="after")
    def _infer_mode(self) -> "PowershellParams":
        """Backward compat: when task_id is set but mode is default 'execute', auto-switch to 'send'."""
        if self.task_id is not None and self.mode == "execute":
            object.__setattr__(self, 'mode', 'send')
        return self

    @model_validator(mode="after")
    def _validate_cmd(self) -> "PowershellParams":
        if self.mode == "execute" and not self.interactive and not self.cmd:
            raise ValueError("cmd cannot be empty unless interactive=True or mode='send'")
        if self.mode == "send":
            if not self.cmd:
                raise ValueError("cmd cannot be empty when mode='send'")
            if not self.task_id:
                raise ValueError("mode='send' requires task_id to identify the target session")
        if self.task_id is not None and self.mode != "send":
            raise ValueError("task_id requires mode='send'")
        return self
        if self.task_id is not None and self.mode != "send":
            raise ValueError("task_id requires mode='send'")
        return self

class Powershell(CallableTool2[PowershellParams]):

    name: str = "Powershell"
    description: str = ""
    params: type[PowershellParams] = PowershellParams

    def __init__(self, session: Session):
        desc = load_desc(Path(__file__).parent / "pwsh_tool.md")
        super().__init__(description=desc)
        self.description += (
            " Accepts `cmd` or `command` parameter. "
            "Output longer than `max_lines` is collapsed via head+tail fold (first N + last N lines, "
            "with middle replaced by a truncation marker). Set `max_lines=None` for unlimited output. "
            + _interactive_scope_text(is_shell=True)
        )
        self._session = session
        if not _bash_tool._should_enable_powershell():
            raise SkipThisTool()

        if sys.platform == "win32":
            self.description += (
                " Windows paths must use backslashes (`\\`) instead of forward slashes (`/`)."
            )

        self._pwsh_path = find_pwsh()
        self._pwsh_fallback_path: str | None = None
        if self._pwsh_path is None:
            # Resolve Windows PowerShell fallback to a full path so that we
            # avoid accidentally picking up a WindowsApps stub at runtime.
            self._pwsh_fallback_path = shutil.which("powershell.exe") or shutil.which("powershell") or "powershell"
            _print_warning(
                "PowerShell 7.x not found on this system; falling back to Windows PowerShell 5.1. "
                "PowerShell 7 syntax will be downgraded automatically, which may change command behavior."
            )

        # Pre-normalize forbidden commands once at init time for O(1) per-call lookup.
        # PowerShell is case-insensitive; normalize to lowercase.
        raw_forbidden = self._session.custom_config.get("config_json", {}).get("forbidden_commands", [])
        self._forbidden_keywords: list[str] = []
        seen: set[str] = set()
        for cmd in raw_forbidden:
            if not isinstance(cmd, str) or not cmd:
                continue
            normalized = " ".join(cmd.split()).lower()
            if normalized not in seen:
                seen.add(normalized)
                self._forbidden_keywords.append(normalized)

    async def __call__(self, params: PowershellParams) -> ToolReturnValue:
        """Execute the PowerShell command via the system PowerShell executable.

        Args:
            params: The parameters specifying the command and its arguments.

        Returns:
            ToolOk on success, ToolError on failure or timeout.
        """
        if params.mode == "send":
            if not params.task_id:
                return ToolError(
                    output="",
                    message="mode='send' requires task_id to identify the target session.",
                    brief="Missing task_id",
                )
            return await self._continue_session(params)

        if not params.interactive and not params.cmd:
            return ToolError(
                output="Empty command.",
                message="No command specified.",
                brief="Empty command",
            )

        # Rewrite known commands through RTK before any PS5.1 syntax transform.
        rtk_cmd, rtk_rewritten = _maybe_rewrite_shell_command_with_rtk(
            params.cmd, params.deduplicate_output
        )
        if self._pwsh_path is not None:
            # PowerShell 7 is available: run the command as-is without syntax transforms.
            cmd = rtk_cmd
            transform_warning = ""
            executable = self._pwsh_path
        else:
            # Fall back to Windows PowerShell 5.1 and downgrade PS7 syntax.
            cmd, transform_warnings = pwsh_transform(rtk_cmd)
            transform_warning = ""
            if transform_warnings:
                warning_lines = "\n".join(w for w in transform_warnings)
                transform_warning = '\n[WARNING]' + warning_lines
            executable = self._pwsh_fallback_path if self._pwsh_fallback_path else "powershell"

        # Lightweight input validation before proceeding.
        # Skip validation for interactive sessions with no initial command
        # (empty cmd is valid in that case — just starts a shell).
        if cmd:
            validation_error = self._validate_command_for_ps(cmd)
            if validation_error:
                return ToolError(
                    output="",
                    message=validation_error + transform_warning,
                    brief="Invalid PowerShell command",
                )

        pattern = self._compile_pattern(params.wait_for_pattern)
        if isinstance(pattern, ToolError):
            return pattern

        if params.cmd and self._forbidden_keywords:
            # PowerShell is case-insensitive: compare lowercased strings.
            normalized_cmd = " ".join(cmd.split()).lower()
            for keyword in self._forbidden_keywords:
                if keyword in normalized_cmd:
                    return ToolError(
                        output="",
                        message=f"`{cmd}` is forbidden by config rule." + transform_warning,
                        brief="Forbidden command",
                    )
        # Refresh PATH/PATHEXT from registry so that tools installed
        # since the last command (e.g. via WinGet) are discoverable.
        if sys.platform == "win32":
            from kimix.utils.windows_env import refresh_env_from_registry
            refresh_env_from_registry()

        if params.interactive:
            ps_args = ["-NoP", "-Exec", "Bypass", "-NoL"]
            if cmd:
                ps_args.extend(["-NoExit", "-Command", _PWSH_CONSOLE_INIT + cmd])
            else:
                ps_args.extend(["-NoExit", "-Command", _PWSH_CONSOLE_INIT])
            process_task = ProcessTask(executable, ps_args, None, _env_with_rg_bin_path(), append_newline=True)
            task_id = await process_task.start(self._session, "pwsh")
            if params.wait_for_pattern is not None and process_task.stream is not None:
                inactivity_timeout = min(30.0, float(params.timeout))
                output, matched, elapsed = await process_task.stream.wait_for_output(
                    timeout=params.timeout, pattern=pattern,
                    inactivity_timeout=inactivity_timeout,
                )
                alive = await process_task.thread_is_alive()
                status = "running" if alive else "completed"
                return await self._format_session_result(
                    task_id, process_task.stream, params, output, status,
                    wait_matched=matched, elapsed_seconds=elapsed,
                    message=(
                        f"Interactive PowerShell started. task_id: `{task_id}`. "
                        "Send 'exit' to close the session."
                    ) + transform_warning,
                    brief="Interactive PowerShell started",
                )
            return ToolOk(
                output="",
                message=(
                    f"Interactive PowerShell started. task_id: `{task_id}`. "
                    "Use task_id to send commands and TaskOutput to read results. "
                    "Send 'exit' to close the session."
                ) + transform_warning,
                brief="Interactive PowerShell started",
            )

        # Build the command line to pass to PowerShell.  Two safety measures:
        #
        # 1. Wrap the user command in ``try{…}catch{…;exit 1}`` so that
        #    terminating errors (e.g. script-terminating ``throw``, or cmdlet
        #    errors when ``$ErrorActionPreference = 'Stop'``) produce a non-zero
        #    exit code instead of silently succeeding.  The catch block echoes
        #    the error and exits with code 1.
        # 2. Append ``; exit $LASTEXITCODE`` so PowerShell preserves the real
        #    native exit code from external programs (otherwise all non-zero
        #    codes are flattened to 1).
        raw_command = (
            _PWSH_CONSOLE_INIT
            + "try{" + cmd + "}catch{$_|Out-String|Write-Error;exit 1}"
            + ";exit $LASTEXITCODE"
        )
        encoded_cmd, param_name, was_encoded = self._maybe_encode_command(raw_command)
        process_task = ProcessTask(
            executable,
            ["-NoP", "-NonI", "-Exec", "Bypass", "-NoL", param_name, encoded_cmd],
            None,
            _env_with_rg_bin_path(),
        )
        task_id = await process_task.start(self._session, "pwsh")

        wait_matched: bool | None = None
        elapsed_seconds: float | None = None
        try:
            if params.wait_for_pattern is not None and process_task.stream is not None:
                inactivity_timeout = min(30.0, float(params.timeout))
                output, wait_matched, elapsed_seconds = await process_task.stream.wait_for_output(
                    timeout=params.timeout, pattern=pattern,
                    inactivity_timeout=inactivity_timeout,
                )
                if await process_task.thread_is_alive():
                    return await self._format_session_result(
                        task_id, process_task.stream, params, output, "running",
                        wait_matched=wait_matched, elapsed_seconds=elapsed_seconds,
                        message=f"`{cmd}` matched pattern and is still running." + transform_warning,
                        brief="Pattern matched",
                    )
            else:
                await process_task.wait_with_monitor(params.timeout)
        except asyncio.CancelledError:
            # The tool call was cancelled (e.g. by a tool-level timeout or
            # shutdown). Stop the subprocess and return a tool error so the
            # conversation stream can continue.
            with contextlib.suppress(asyncio.CancelledError):
                await process_task.stop()
            from kimix.tools.background.utils import remove_task_id
            remove_task_id(self._session, task_id)
            output = await process_task.stream.get_output() if process_task.stream else ""
            output = await _maybe_export_output_async(output)
            transform_warning = transform_warning or ""
            return ToolError(
                output=output,
                message=f"`{cmd}` was cancelled." + transform_warning,
                brief="Command cancelled",
            )

        if await process_task.thread_is_alive():
            output = await process_task.stream.pop_output() if process_task.stream else ""
            output = await _maybe_export_output_async(output)
            return ToolError(
                output=output,
                message=f"`{cmd}` Running in background. task_id: `{task_id}`. use `TaskOutput`." + transform_warning,
                brief="Timeout",
            )

        from kimix.tools.background.utils import remove_task_id
        remove_task_id(self._session, task_id)

        output = await process_task.stream.pop_output() if process_task.stream else ""
        stream = process_task.stream
        success = await stream.success() if stream else False
        real_exit_code = stream.exit_code if stream else None

        # Unify success/error path: always pass the real exit code.
        processed, output_path, output_truncated, original_path = await self._process_output(
            cmd, params, output, rtk_rewritten=rtk_rewritten
        )
        block = _build_session_output_block(
            task_id=task_id,
            status="completed",
            output=processed,
            exit_code=real_exit_code,
            wait_matched=wait_matched,
            elapsed_seconds=elapsed_seconds,
            output_path=output_path,
            output_truncated=output_truncated,
            original_path=original_path,
        )
        elapsed = stream.process_elapsed if stream else None

        if not success:
            msg = f"`{cmd}` failed."
            if elapsed is not None:
                msg += f" ({elapsed:.1f}s)"
            return ToolError(output=block, message=msg + transform_warning, brief="Command execution failed")

        msg = (f"[rtk] `{cmd}` success." if rtk_rewritten else f"`{cmd}` success.")
        if elapsed is not None:
            msg += f" ({elapsed:.1f}s)"
        return ToolOk(
            output=block,
            message=msg + transform_warning,
            brief=f"Command executed successfully",
            display_block=ShellDisplayBlock(language="powershell", command=cmd),
        )

    @staticmethod
    def _validate_command_for_ps(cmd: str) -> str | None:
        """Lightweight validation of a PowerShell command string.

        Checks for patterns that are known to cause argument-parsing problems
        when passed via ``-Command``:

        * Command strings that are empty or whitespace-only.
        * Unbalanced double quotes ``"`` (odd count of ``"`` outside of safe
          contexts).  This is a best-effort heuristic — it does not account
          for escaped quotes or nested strings.

        Returns ``None`` when the command passes validation, or an error
        message string explaining the problem.
        """
        if not cmd or not cmd.strip():
            return "Command is empty or whitespace-only."

        # Check for obviously unbalanced double quotes (simple count).
        # PowerShell allows escaped quotes inside ``"..."`` via ``, but a
        # simple parity check still catches many user errors.
        dq_count = cmd.count('"')
        if dq_count % 2 != 0:
            return (
                "Command contains an unbalanced double quote character. "
                "This may cause PowerShell to misinterpret the command. "
                "Consider escaping or removing the extra quote."
            )

        return None

    @staticmethod
    def _maybe_encode_command(full_cmd: str) -> tuple[str, str, bool]:
        """Return ``(command_or_encoded, param_name, was_encoded)``.

        When *full_cmd* exceeds 8000 characters the command is Base64-encoded
        (UTF-16 LE) and returned with ``-EncodedCommand`` (short form ``-Enc``)
        to avoid the Win32 ``CreateProcess`` command-line length limit.
        Otherwise the original string is returned with ``-Command`` (short form
        ``-C``).
        """
        if len(full_cmd) > 8000:
            encoded = base64.b64encode(full_cmd.encode("utf-16-le")).decode("ascii")
            return encoded, "-Enc", True
        return full_cmd, "-C", False

    def _compile_pattern(self, wait_for_pattern: str | None) -> re.Pattern[str] | ToolError:
        if wait_for_pattern is None:
            return None
        try:
            return re.compile(wait_for_pattern)
        except re.error as e:
            return ToolError(
                output="",
                message=f"Invalid wait_for_pattern: {e}",
                brief="Invalid pattern",
            )

    async def _continue_session(self, params: PowershellParams) -> ToolReturnValue:
        """Send input to an existing PowerShell session and optionally wait for output."""
        from kimix.tools.background.utils import get_all_tasks

        tasks = get_all_tasks(self._session)
        task_id = params.task_id.strip() if params.task_id else ""
        stream = tasks.get(task_id)
        if stream is None:
            started = [tid for tid, s in tasks.items() if await s.is_started()]
            if not started:
                return ToolError(
                    output="",
                    message=f"Task '{params.task_id}' not found. No running tasks.",
                    brief="Task not found",
                )
            return ToolError(
                output="",
                message=(
                    f"Task '{params.task_id}' not found. "
                    f"Available tasks: [{', '.join(started)}]"
                ),
                brief=f"Task '{params.task_id}' not found",
            )

        pattern = self._compile_pattern(params.wait_for_pattern)
        if isinstance(pattern, ToolError):
            return pattern

        await stream.pop_output()

        rtk_cmd, rtk_rewritten = _maybe_rewrite_shell_command_with_rtk(
            params.cmd, params.deduplicate_output
        )
        input_text = rtk_cmd
        if not input_text.endswith("\n"):
            input_text += "\n"
        if not await stream.input(input_text):
            return ToolError(
                output="",
                message=f"Failed to send input to task '{task_id}'",
                brief="Send input failed",
            )

        inactivity_timeout = min(30.0, float(params.timeout))
        output, matched, elapsed = await stream.wait_for_output(
            timeout=params.timeout, pattern=pattern,
            inactivity_timeout=inactivity_timeout,
        )
        alive = await stream.thread_is_alive()
        status = "running" if alive else "completed"
        return await self._format_session_result(
            task_id, stream, params, output, status,
            wait_matched=matched, elapsed_seconds=elapsed,
            message=(f"[rtk] Data sent to `{task_id}`. Status: {status}." if rtk_rewritten else f"Data sent to `{task_id}`. Status: {status}."),
            brief="Data sent and output retrieved",
            rtk_rewritten=rtk_rewritten,
        )

    async def _process_output(
        self, command: str, params: PowershellParams, output: str, rtk_rewritten: bool = False
    ) -> tuple[str, str | None, bool, str | None]:
        """Summarize/export long output. Returns (display_output, path, truncated, original_path)."""
        # Run token filter pipeline (dedup, truncate)
        output, original_path = await _token_filter_output(
            output,
            token_kill=params.deduplicate_output,
            max_lines=params.max_lines,
            rtk_rewritten=rtk_rewritten,
        )
        output_truncated = False
        if len(output) > 65536:
            output = await _summarize_long_output_async(self._session, command, output)
            output_truncated = True
        output = await _maybe_export_output_async(output)
        output_path = _extract_export_path(output)
        return output, output_path, output_truncated, original_path

    async def _format_session_result(
        self,
        task_id: str,
        stream: 'BackgroundStream' | None,
        params: PowershellParams,
        output: str,
        status: str,
        *,
        wait_matched: bool | None,
        elapsed_seconds: float | None,
        message: str,
        brief: str,
        rtk_rewritten: bool = False,
    ) -> ToolReturnValue:
        """Build a ToolOk response with a structured output block."""
        processed, output_path, output_truncated, original_path = await self._process_output(
            params.cmd, params, output, rtk_rewritten=rtk_rewritten
        )
        if status != "completed":
            real_exit_code = None
        else:
            real_exit_code = stream.exit_code if stream else None
            if real_exit_code is None:
                real_exit_code = 0 if await stream.success() else None
        block = _build_session_output_block(
            task_id=task_id,
            status=status,
            output=processed,
            exit_code=real_exit_code,
            wait_matched=wait_matched,
            elapsed_seconds=elapsed_seconds,
            output_path=output_path,
            output_truncated=output_truncated,
            original_path=original_path,
        )
        return ToolOk(output=block, message=message, brief=brief)
