"""PowerShell tool that executes commands via the system PowerShell executable."""

import asyncio
import pybase64 as base64
import contextlib
import functools
import os
from pathlib import Path
import regex as re
import shutil
import subprocess
import sys
from typing import TYPE_CHECKING, Literal

from kimi_agent_sdk import CallableTool2, ToolError, ToolOk, ToolReturnValue
from pydantic import AliasChoices, BaseModel, Field, model_validator
from kimi_cli.session import Session
from kimi_cli.tools import SkipThisTool
from kimi_cli.tools.utils import load_desc
from kimi_cli.tools.display import ShellDisplayBlock
from kimix.tools.file.bash import bash_tool as _bash_tool
from kimix.tools.file.bash.process_pwsh import pwsh_transform
from kimix.tools.file.bash.pwsh_fix import fix_pwsh_command
from kimix.tools.common import (
    _build_session_output_block,
    _command_saved_message,
    _env_with_rg_bin_path,
    _extract_export_path,
    _interactive_scope_text,
    _maybe_export_output_async,
    _maybe_export_rtk_original_async,
    _maybe_rewrite_shell_command_with_rtk,
    _original_saved_message,
    _save_original_output_async,
    _summarize_long_output_async,
    _token_filter_output,
    ProcessTask,
)
from kimix.tools.prompt_common import (
    accepts_alias_text,
    max_lines_field,
    mode_field,
    normalize_mode_validator,
    shell_cmd_required_validator,
    task_id_field,
    timeout_field,
    wait_for_pattern_field,
)
from kimix.tools.file.bash.output_enhance import (
    annotate_failure,
    interpret_exit_code,
    is_expected_exit,
    redact_sensitive_output,
)
from kimix.tools.file.bash.safety import (
    check_hardline_blocked,
    foreground_background_guidance,
    self_kill_hint,
)

if TYPE_CHECKING:
    from kimi_agent_sdk import CallableTool2 as _CallableTool2

# Console initialization prepended to every PowerShell command. Sets UTF-8
# output encoding and treats Ctrl+C as regular input so that console control
# signals generated by or sent to the PowerShell subprocess do not propagate
# back and raise KeyboardInterrupt in the parent Python process.
_PWSH_CONSOLE_INIT = (
    "[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;"
    "$OutputEncoding=[System.Text.Encoding]::UTF8;"
    "try{[Console]::TreatControlCAsInput=$true}catch{};"
)

def _print_warning(message: str) -> None:
    """Print a yellow WARNING message to stderr."""
    yellow = "\033[33m"
    reset = "\033[0m"
    print(f"{yellow}WARNING: {message}{reset}", file=sys.stderr, flush=True)

def _pwsh_major_version(path: str) -> int | None:
    """Return the major version reported by a PowerShell executable, or None."""
    try:
        output = subprocess.check_output(
            [path, "-NoP", "-NonI", "-C", "$PSVersionTable.PSVersion.Major"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=3,
        ).strip()
        return int(output)
    except (OSError, subprocess.TimeoutExpired, ValueError):
        return None


def _is_windows_apps_stub(path: str) -> bool:
    """Return True if *path* points into the WindowsApps directory (Store stub)."""
    return "WindowsApps" in os.path.normpath(path).split(os.sep)


def _where_candidates(name: str) -> list[str]:
    """Return candidate paths reported by ``where.exe <name>``, excluding WindowsApps stubs."""
    try:
        result = subprocess.run(
            ["where.exe", name],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []
    if result.returncode != 0:
        return []
    return [
        line.strip() for line in result.stdout.splitlines()
        if line.strip() and not _is_windows_apps_stub(line.strip())
    ]


def _common_fixed_pwsh_paths() -> list[str]:
    """Return well-known PowerShell 7 installation paths for the current platform.

    On Windows these are checked *before* ``where.exe`` results so that the
    genuine MSI install is preferred over Store execution aliases.
    """
    if sys.platform == "win32":
        return [
            r"C:\Program Files\PowerShell\7\pwsh.exe",
            r"C:\Program Files (x86)\PowerShell\7\pwsh.exe",
        ]
    return [
        "/opt/microsoft/powershell/7/pwsh",
        "/usr/local/bin/pwsh",
        "/usr/bin/pwsh",
    ]


def _is_versioned_pwsh7_install(path: str) -> bool:
    """Return True if *path* is a PowerShell 7 versioned install directory layout.

    Microsoft always installs PowerShell 7.x into a ``PowerShell\\7`` (Windows)
    or ``.../7/`` (POSIX) directory, so an executable at such a path is known
    to be version 7+ without having to spawn a subprocess to ask it.
    """
    norm = os.path.normcase(os.path.normpath(path))
    if sys.platform == "win32":
        return norm.endswith(os.path.normcase(r"PowerShell\7\pwsh.exe"))
    return norm.endswith("/7/pwsh")


@functools.lru_cache(maxsize=1)
def find_pwsh() -> str | None:
    """Find PowerShell 7.x on the current platform.

    Resolution order:
      1. Common fixed installation paths (MSI install on Windows). These live
         in a versioned ``7`` directory, so no version probe is needed — this
         avoids spawning subprocesses in the common case (fast startup).
      2. ``pwsh`` / ``pwsh.exe`` on PATH (via ``shutil.which``).
      3. ``where.exe pwsh.exe`` on Windows (WindowsApps stubs filtered out).

    Returns the absolute path to a PowerShell 7+ executable, or ``None`` if
    only Windows PowerShell 5.1 (or no PowerShell) is available.
    """
    # 1. Fixed common install locations (checked first so MSI install is
    #    preferred over Store execution aliases on Windows). The versioned
    #    install directory guarantees major version 7, so return immediately
    #    without spawning a version-probe subprocess.
    for candidate in _common_fixed_pwsh_paths():
        if os.path.exists(candidate) and _is_versioned_pwsh7_install(candidate):
            return candidate

    candidates: list[str] = []

    # 2. PATH
    if sys.platform == "win32":
        names = ["pwsh.exe", "pwsh"]
    else:
        names = ["pwsh"]
    for name in names:
        resolved = shutil.which(name)
        if resolved:
            candidates.append(resolved)

    # 3. where.exe (Windows only) — WindowsApps stubs already filtered.
    #    A single probe is enough: ``where.exe pwsh`` also matches pwsh.exe.
    #    Skip the extra subprocess entirely when PATH lookup already found
    #    candidates; where.exe is only a fallback for pwsh not on PATH.
    if sys.platform == "win32" and not candidates:
        candidates.extend(_where_candidates(names[0]))

    seen: set[str] = set()
    for candidate in candidates:
        candidate = shutil.which(candidate) or candidate
        if not os.path.exists(candidate):
            continue
        norm = os.path.normcase(os.path.abspath(candidate))
        if norm in seen:
            continue
        seen.add(norm)
        if _is_versioned_pwsh7_install(candidate):
            return candidate
        major = _pwsh_major_version(candidate)
        if major is not None and major >= 7:
            return candidate

    return None


class PowershellParams(BaseModel):
    """Parameters for the Powershell tool — execute a PowerShell command."""

    model_config = {"populate_by_name": True}

    command: str = Field(
        default="",
        validation_alias=AliasChoices("command", "cmd"),
        description=(
            "PowerShell command, or path to an existing `.ps1` script file, "
            "executed via PowerShell. "
            + accepts_alias_text("command", "cmd", word=False)
        ),
    )
    description: str | None = Field(
        default=None,
        description=(
            "Clear, concise description of what the command does in active "
            "voice, 5-10 words (shown in the UI)."
        ),
    )
    timeout: int = Field(
        default=30,
        validation_alias=AliasChoices("timeout", "timeoutMs"),
        ge=1,
        le=900,
        description=(
            "Timeout in seconds; kills the command on expiry. "
            + accepts_alias_text("timeout", "timeoutMs", word=False)
        ),
    )
    workdir: str | None = Field(
        default=None,
        description=(
            "Working directory for this command. Defaults to the session "
            "workspace; a relative path is resolved against it."
        ),
    )
    run_in_background: bool = Field(
        default=False,
        description=(
            "Run in the background and return a job id immediately "
            "(read with job_output; stop with job_output action='kill'). "
            "No timeout applies."
        ),
    )
    sandbox_permissions: Literal["workspace-write", "danger-full-access"] | None = Field(
        default=None,
        description=(
            "The wider sandbox mode this command needs (`workspace-write` or "
            "`danger-full-access`). Only valid as a one-shot retry of a command "
            "the sandbox just denied; requires justification and user approval."
        ),
    )
    justification: str | None = Field(
        default=None,
        description=(
            "Required with sandbox_permissions: one sentence for the user "
            "explaining why this exact command needs the wider access."
        ),
    )
    mode: Literal["execute", "send", "interactive"] = mode_field(
        execute_desc="run now.",
        send_desc="background, return task_id.",
        interactive_desc="persistent REPL, return task_id.",
    )
    task_id: str | None = task_id_field("cmd")
    wait_for_pattern: str | None = wait_for_pattern_field()
    max_lines: int | None = max_lines_field()

    @model_validator(mode="before")
    @classmethod
    def _normalize_mode(cls, data: dict) -> dict:
        """Convert deprecated boolean flags and mode aliases to canonical names."""
        data = normalize_mode_validator(data)
        if isinstance(data, dict):
            # Legacy `timeoutMs` (milliseconds) -> canonical `timeout` (seconds).
            if "timeout" not in data and data.get("timeoutMs") is not None:
                data = {**data, "timeout": max(1, int(data["timeoutMs"]) // 1000)}
            if data.get("run_in_background", False):
                data["mode"] = "send"
        return data

    _validate_cmd = shell_cmd_required_validator("command")

class Powershell(CallableTool2[PowershellParams]):

    name: str = "pwsh"
    description: str = ""
    params: type[PowershellParams] = PowershellParams

    def __init__(self, session: Session):
        desc = load_desc(Path(__file__).parent / "pwsh_tool.md")
        super().__init__(description=desc)
        self.description += " " + _interactive_scope_text(is_shell=True)
        self._session = session
        if not _bash_tool._should_enable_powershell():
            raise SkipThisTool()

        if sys.platform == "win32":
            self.description += (
                " Windows paths must use backslashes (`\\`) instead of forward slashes (`/`)."
            )

        # PowerShell resolution (which may spawn version-probe subprocesses)
        # is deferred to first use so tool loading stays fast at startup.
        self._pwsh_path: str | None = None
        self._pwsh_fallback_path: str | None = None
        self._pwsh_resolved = False

        # Pre-normalize forbidden commands once at init time for O(1) per-call lookup.
        # PowerShell is case-insensitive; normalize to lowercase.
        raw_forbidden = self._session.custom_config.get("config_json", {}).get("forbidden_commands", [])
        self._forbidden_keywords: list[str] = []
        seen: set[str] = set()
        for cmd in raw_forbidden:
            if not isinstance(cmd, str) or not cmd:
                continue
            normalized = " ".join(cmd.split()).lower()
            if normalized not in seen:
                seen.add(normalized)
                self._forbidden_keywords.append(normalized)

        # Config gates for the hardline safety floor and secret redaction
        # (both default on; explicitly set False to disable).
        shell_cfg = self._session.custom_config.get("config_json", {}).get("shell", {})
        if isinstance(shell_cfg, dict):
            self._hardline_enabled = shell_cfg.get("hardline", True)
            self._redact_secrets = shell_cfg.get("redact_secrets", True)
            self._self_kill_guard_enabled = shell_cfg.get("self_kill_guard", True)
        else:
            self._hardline_enabled = True
            self._redact_secrets = True
            self._self_kill_guard_enabled = True

        # Proactive self-kill hint: make the agent's own PID visible up front
        # so the model avoids targeting it; the guard below blocks attempts.
        self.description += (
            f" Safety: runs in the agent process (PID {os.getpid()}); never kill that PID, "
            "its parents, or this process's image — the self-kill guard blocks it."
        )

    def _hardline_blocked(self, command: str) -> ToolError | None:
        r"""Return a ToolError when *command* hits the unconditional hardline floor.

        Applies deobfuscation variants (quotes/backslash-escapes/case tricks)
        before matching, so ``r\m -rf /``, ``rm "" -rf /`` and ``Rm -Rf /``
        are all blocked.  Skipped entirely when the ``shell.hardline`` config
        gate is explicitly ``False``.
        """
        if not self._hardline_enabled or not command:
            return None
        blocked, desc = check_hardline_blocked(command)
        if not blocked:
            return None
        return ToolError(
            output="",
            message=(
                f"Blocked (hardline): {desc}. This command cannot be executed "
                "via the agent."
            ),
            brief="Blocked (hardline)",
        )

    def _self_kill_blocked(self, command: str) -> ToolError | None:
        r"""Return a ToolError when *command* would kill the agent process itself.

        The LLM backend sometimes resolves the wrong PID (or uses a broad
        image-name/pattern kill such as ``taskkill /IM python.exe /F`` or
        ``pkill -f python``), terminating the very process hosting the agent.
        The guard compares kill targets against the current PID, its ancestor
        PIDs, and the agent's own image name, returning a smart hint instead
        of executing.  Skipped when the ``shell.self_kill_guard`` config gate
        is explicitly ``False``.
        """
        if not self._self_kill_guard_enabled or not command:
            return None
        hint = self_kill_hint(command)
        if hint is None:
            return None
        return ToolError(
            output="",
            message=f"Blocked (self-kill guard): {hint}",
            brief="Blocked (self-kill guard)",
        )

    def _resolve_pwsh(self) -> None:
        """Resolve the PowerShell executable paths on first use."""
        if self._pwsh_resolved:
            return
        self._pwsh_resolved = True
        self._pwsh_path = find_pwsh()
        if self._pwsh_path is None:
            # Resolve Windows PowerShell fallback to a full path so that we
            # avoid accidentally picking up a WindowsApps stub at runtime.
            from kimix.tools.file.bash import shell_common

            self._pwsh_fallback_path = shell_common.pwsh_executable()
            _print_warning(
                "PowerShell 7.x not found on this system; falling back to Windows PowerShell 5.1. "
                "PowerShell 7 syntax will be downgraded automatically, which may change command behavior."
            )

    async def __call__(self, params: PowershellParams) -> ToolReturnValue:
        """Execute the PowerShell command via the system PowerShell executable.

        Args:
            params: The parameters specifying the command and its arguments.

        Returns:
            ToolOk on success, ToolError on failure or timeout.
        """
        # Hardline safety floor: never spawn a process for destructive commands.
        blocked = self._hardline_blocked(params.command)
        if blocked is not None:
            return blocked
        # Self-kill guard: never run a command that kills the agent process.
        blocked = self._self_kill_blocked(params.command)
        if blocked is not None:
            return blocked

        # Early dispatch: continue an existing session
        if params.task_id is not None:
            return await self._continue_session(params)

        if params.mode == "send":
            return await self._execute_background(params)

        if params.mode != "interactive" and not params.command:
            return ToolError(
                output="Empty command.",
                message="No command specified.",
                brief="Empty command",
            )

        # Rewrite known commands through RTK before any PS5.1 syntax transform.
        rtk_cmd, rtk_rewritten = _maybe_rewrite_shell_command_with_rtk(
            params.command, True, pwsh=True
        )
        self._resolve_pwsh()
        if self._pwsh_path is not None:
            # PowerShell 7 is available: run the command as-is without syntax transforms.
            cmd = rtk_cmd
            transform_warning = ""
            executable = self._pwsh_path
        else:
            # Fall back to Windows PowerShell 5.1 and downgrade PS7 syntax.
            cmd, transform_warnings = pwsh_transform(rtk_cmd)
            transform_warning = ""
            if transform_warnings:
                warning_lines = "\n".join(w for w in transform_warnings)
                transform_warning = '\n[WARNING]' + warning_lines
            executable = self._pwsh_fallback_path if self._pwsh_fallback_path else "powershell"

        # Lightweight input validation before proceeding.
        # Skip validation for interactive sessions with no initial command
        # (empty cmd is valid in that case — just starts a shell).
        if cmd:
            validation_error = self._validate_command_for_ps(cmd)
            # The naive parity check rejects many *valid* commands (e.g. a
            # double quote inside a single-quoted string, a here-string, a
            # comment or a backtick-escaped quote).  Run the PowerShell-aware
            # parser: it either verifies the command is legal, repairs it by
            # appending the missing closing token (warning instead of error),
            # or reports it as unrepairable.
            fix = fix_pwsh_command(cmd)
            if fix is None:
                return ToolError(
                    output="",
                    message=(validation_error or "Invalid PowerShell command.") + transform_warning,
                    brief="Invalid PowerShell command",
                )
            if validation_error:
                # The naive check flagged the command; the parser verified or
                # repaired it — proceed with a warning instead of an error.
                cmd = fix.command
                if fix.warning:
                    transform_warning += "\n[WARNING] " + fix.warning
                else:
                    transform_warning += (
                        "\n[WARNING] Command has an apparently unbalanced quote, "
                        "but the PowerShell-aware parser verified it is valid; "
                        "executing as-is."
                    )
            elif fix.changed:
                # Validation passed, but the parser made the command safe for
                # the try/catch wrapper (trailing comment, `--%` marker, or an
                # unclosed string the parity check cannot see).
                cmd = fix.command
                transform_warning += "\n[WARNING] " + fix.warning

        pattern = self._compile_pattern(params.wait_for_pattern)
        if isinstance(pattern, ToolError):
            return pattern

        if params.command and self._forbidden_keywords:
            # PowerShell is case-insensitive: compare lowercased strings.
            normalized_cmd = " ".join(cmd.split()).lower()
            for keyword in self._forbidden_keywords:
                if keyword in normalized_cmd:
                    return ToolError(
                        output="",
                        message=f"`{cmd}` is forbidden by config rule." + transform_warning,
                        brief="Forbidden command",
                    )
        # Re-check the prepared text (rtk-rewritten / PS5.1-transformed) too.
        blocked = self._hardline_blocked(cmd)
        if blocked is not None:
            return blocked
        blocked = self._self_kill_blocked(cmd)
        if blocked is not None:
            return blocked
        # Refresh PATH/PATHEXT from registry so that tools installed
        # since the last command (e.g. via WinGet) are discoverable.
        if sys.platform == "win32":
            from kimix.utils.windows_env import refresh_env_from_registry
            refresh_env_from_registry()

        if params.mode == "interactive":
            ps_args = ["-NoP", "-Exec", "Bypass", "-NoL"]
            if cmd:
                ps_args.extend(["-NoExit", "-Command", _PWSH_CONSOLE_INIT + cmd])
            else:
                ps_args.extend(["-NoExit", "-Command", _PWSH_CONSOLE_INIT])
            process_task = ProcessTask(executable, ps_args, None, _env_with_rg_bin_path(), append_newline=True)
            task_id = await process_task.start(self._session, "pwsh")
            if process_task.stream is not None:
                process_task.stream.format_output = functools.partial(
                    self._format_background_output,
                    cmd,
                    params,
                    rtk_rewritten=rtk_rewritten,
                    transform_warning=transform_warning,
                )
            if params.wait_for_pattern is not None and process_task.stream is not None:
                from kimix.tools.background.utils import DEFAULT_INACTIVITY_TIMEOUT
                inactivity_timeout = min(DEFAULT_INACTIVITY_TIMEOUT, float(params.timeout))
                output, matched, elapsed = await process_task.stream.wait_for_output(
                    timeout=params.timeout, pattern=pattern,
                    inactivity_timeout=inactivity_timeout,
                )
                alive = await process_task.thread_is_alive()
                status = "running" if alive else "completed"
                return await self._format_session_result(
                    task_id, process_task.stream, params, output, status,
                    wait_matched=matched, elapsed_seconds=elapsed,
                    message=(
                        f"Interactive PowerShell started. task_id: `{task_id}`. "
                        "Use task_id to send commands and job_output to read results. "
                        "Send 'exit' to close the session."
                    ) + transform_warning,
                    brief="Interactive PowerShell started",
                )
            return ToolOk(
                output="",
                message=(
                    f"Interactive PowerShell started. task_id: `{task_id}`. "
                    "Use task_id to send commands and job_output to read results. "
                    "Send 'exit' to close the session."
                ) + transform_warning,
                brief="Interactive PowerShell started",
            )

        # Build the command line to pass to PowerShell.  Two safety measures:
        #
        # 1. Wrap the user command in ``try{…}catch{…;exit 1}`` so that
        #    terminating errors (e.g. script-terminating ``throw``, or cmdlet
        #    errors when ``$ErrorActionPreference = 'Stop'``) produce a non-zero
        #    exit code instead of silently succeeding.  The catch block echoes
        #    the error and exits with code 1.
        # 2. Append ``; exit $LASTEXITCODE`` so PowerShell preserves the real
        #    native exit code from external programs (otherwise all non-zero
        #    codes are flattened to 1).
        from kimix.tools.file.bash import shell_common

        # Report semantics: each call runs in a fresh pwsh process, so a
        # requested workdir is applied with Set-Location instead of relying
        # on persisted cwd state.
        if params.workdir:
            workdir = params.workdir.replace("'", "''")
            cmd = f"Set-Location -LiteralPath '{workdir}'; {cmd}"

        raw_command = shell_common.wrap_pwsh_command(cmd)
        encoded_cmd, param_name, was_encoded = self._maybe_encode_command(raw_command)
        process_task = ProcessTask(
            executable,
            [*shell_common.PWSH_ONESHOT_FLAGS, param_name, encoded_cmd],
            None,
            _env_with_rg_bin_path(),
        )
        task_id = await process_task.start(self._session, "pwsh")
        if process_task.stream is not None:
            process_task.stream.format_output = functools.partial(
                self._format_background_output,
                cmd,
                params,
                rtk_rewritten=rtk_rewritten,
                transform_warning=transform_warning,
            )

        wait_matched: bool | None = None
        elapsed_seconds: float | None = None
        # Seconds actually waited by the plain (no-pattern) monitor; used to
        # report an accurate "no output after Ns" hint (the inactivity early
        # return can fire well before ``params.timeout``).
        waited_seconds: float | None = None
        try:
            if params.wait_for_pattern is not None and process_task.stream is not None:
                from kimix.tools.background.utils import DEFAULT_INACTIVITY_TIMEOUT
                inactivity_timeout = min(DEFAULT_INACTIVITY_TIMEOUT, float(params.timeout))
                output, wait_matched, elapsed_seconds = await process_task.stream.wait_for_output(
                    timeout=params.timeout, pattern=pattern,
                    inactivity_timeout=inactivity_timeout,
                )
                if await process_task.thread_is_alive():
                    if wait_matched:
                        return await self._format_session_result(
                            task_id, process_task.stream, params, output, "running",
                            wait_matched=wait_matched, elapsed_seconds=elapsed_seconds,
                            message=(
                                f"Pattern matched; still running. task_id: `{task_id}`. "
                                "Use `job_output` to read more output."
                            ) + transform_warning,
                            brief="Pattern matched",
                        )
                    # The pattern never matched within the timeout.  Keep the
                    # task running only for long-running commands; otherwise
                    # kill the tree like the plain-timeout branch so no zombie
                    # background task is left behind.
                    guidance = foreground_background_guidance(params.command)
                    if guidance is not None:
                        return await self._format_session_result(
                            task_id, process_task.stream, params, output, "running",
                            wait_matched=wait_matched, elapsed_seconds=elapsed_seconds,
                            message=(
                                f"Running in background. task_id: `{task_id}`. "
                                f"{guidance}" + transform_warning
                            ),
                            brief="Pattern matched",
                        )
                    return await self._stop_after_timeout(
                        process_task,
                        task_id,
                        output,
                        f"Command timed out after {params.timeout}s without matching pattern" + transform_warning,
                    )
            else:
                _completed, waited_seconds, _inactivity_timed_out = (
                    await process_task.wait_with_monitor(params.timeout)
                )
        except asyncio.CancelledError:
            # The tool call was cancelled (e.g. by a tool-level timeout or
            # shutdown). Stop the subprocess and return a tool error so the
            # conversation stream can continue.
            with contextlib.suppress(asyncio.CancelledError):
                await process_task.stop()
            from kimix.tools.background.utils import remove_task_id
            remove_task_id(self._session, task_id)
            output = await process_task.stream.get_output() if process_task.stream else ""
            output = await _maybe_export_output_async(output)
            transform_warning = transform_warning or ""
            return ToolError(
                output=output,
                message="Cancelled" + transform_warning,
                brief="Command cancelled",
            )

        if await process_task.thread_is_alive():
            output = await process_task.stream.pop_output() if process_task.stream else ""
            guidance = foreground_background_guidance(params.command)
            if guidance is not None:
                # Long-running command (server/watcher/trailing `&`): keep the
                # process running and hand the task id to the model so it can
                # wait for it with ``job_output`` (or stop it).
                output = await _maybe_export_output_async(output)
                return ToolError(
                    output=output,
                    message=(
                        f"Running in background. task_id: `{task_id}`. "
                        f"{guidance}" + transform_warning
                    ),
                    brief="Timeout",
                )
            if not output:
                # Still running with no output at all: keep this quiet
                # long-running task in the background and hand the task id over
                # so the model can wait for it with ``job_output``.
                waited = waited_seconds if waited_seconds is not None else params.timeout
                return ToolError(
                    output="",
                    message=(
                        f"No output after {waited:.0f}s; command still running. "
                        f"task_id: `{task_id}`. Use `job_output` (wait=true) to "
                        "wait for it."
                    ) + transform_warning,
                    brief="Timeout",
                )
            # The command produced output and then stalled: kill the tree and
            # report a definitive timeout instead of leaving a zombie task.
            return await self._stop_after_timeout(
                process_task,
                task_id,
                output,
                f"Command timed out after {params.timeout}s" + transform_warning,
            )

        from kimix.tools.background.utils import remove_task_id
        remove_task_id(self._session, task_id)

        output = await process_task.stream.pop_output() if process_task.stream else ""
        stream = process_task.stream
        success = await stream.success() if stream else False
        real_exit_code = stream.exit_code if stream else None

        # Exit-code semantics + failure hints run on the raw output (the
        # redacted text is what gets displayed/exported below).
        meaning = interpret_exit_code(params.command, real_exit_code)
        hint = annotate_failure(output, params.command, real_exit_code)
        expected = is_expected_exit(params.command, real_exit_code)

        # Unify success/error path: always pass the real exit code.
        processed, output_path, output_truncated, original_path = await self._process_output(
            cmd, params, output, rtk_rewritten=rtk_rewritten
        )
        block = _build_session_output_block(
            task_id=task_id,
            status="completed",
            output=processed,
            exit_code=real_exit_code,
            exit_code_meaning=meaning,
            failure_hint=hint,
            wait_matched=wait_matched,
            elapsed_seconds=elapsed_seconds,
            output_path=output_path,
            output_truncated=output_truncated,
            original_path=original_path,
        )
        elapsed = stream.process_elapsed if stream else None

        suffix = _original_saved_message(original_path)
        if not success and not expected:
            msg = "failed" + (f" Hint: {hint}" if hint else "")
            msg += transform_warning
            # Long failing commands are preserved as a re-runnable `.ps1` script
            # in the shared temp folder so the exact source is never lost.
            cmd_suffix = _command_saved_message(params.command, ".ps1", "PowerShell")
            if cmd_suffix:
                msg = f"{msg} {cmd_suffix}"
            if suffix:
                msg = f"{msg} {suffix}"
            return ToolError(output=block, message=msg, brief="Command execution failed")

        if not success:
            # Expected/benign non-zero exit (grep "no matches", diff "files
            # differ"): report the meaning instead of "failed ... run it again".
            msg = (meaning or "expected non-zero exit") + transform_warning
        else:
            msg = "[rtk] success" if rtk_rewritten else "success"
            msg += transform_warning
        if suffix:
            msg = f"{msg} {suffix}"
        return ToolOk(
            output=block,
            message=msg,
            brief=f"Command executed successfully",
            display_block=ShellDisplayBlock(language="powershell"),
        )

    @staticmethod
    def _validate_command_for_ps(cmd: str) -> str | None:
        """Lightweight validation of a PowerShell command string.

        Checks for patterns that are known to cause argument-parsing problems
        when passed via ``-Command``:

        * Command strings that are empty or whitespace-only.
        * Unbalanced double quotes ``"`` (odd count of ``"`` outside of safe
          contexts).  This is a best-effort heuristic — it does not account
          for escaped quotes or nested strings, so ``__call__`` hands the
          command to :func:`kimix.tools.file.bash.pwsh_fix.fix_pwsh_command`
          which follows PowerShell's real quoting rules and either verifies
          the command is legal, repairs it, or keeps this error.

        Returns ``None`` when the command passes validation, or an error
        message string explaining the problem.
        """
        if not cmd or not cmd.strip():
            return "Command is empty or whitespace-only."

        # Check for obviously unbalanced double quotes (simple count).
        # PowerShell allows escaped quotes inside ``"..."`` via ``, but a
        # simple parity check still catches many user errors.
        dq_count = cmd.count('"')
        if dq_count % 2 != 0:
            return (
                "Command contains an unbalanced double quote character. "
                "This may cause PowerShell to misinterpret the command. "
                "Consider escaping or removing the extra quote."
            )

        return None

    @staticmethod
    def _maybe_encode_command(full_cmd: str) -> tuple[str, str, bool]:
        """Return ``(command_or_encoded, param_name, was_encoded)``.

        When *full_cmd* exceeds 8000 characters the command is Base64-encoded
        (UTF-16 LE) and returned with ``-EncodedCommand`` (short form ``-Enc``)
        to avoid the Win32 ``CreateProcess`` command-line length limit.
        Otherwise the original string is returned with ``-Command`` (short form
        ``-C``).
        """
        if len(full_cmd) > 8000:
            encoded = base64.b64encode(full_cmd.encode("utf-16-le")).decode("ascii")
            return encoded, "-Enc", True
        return full_cmd, "-C", False

    def _compile_pattern(self, wait_for_pattern: str | None) -> re.Pattern[str] | ToolError:
        if wait_for_pattern is None:
            return None
        try:
            return re.compile(wait_for_pattern)
        except re.error as e:
            return ToolError(
                output="",
                message=f"Invalid wait_for_pattern: {e}",
                brief="Invalid pattern",
            )

    async def _stop_after_timeout(
        self,
        process_task: ProcessTask,
        task_id: str,
        output: str,
        message: str,
    ) -> ToolError:
        """Kill a foreground command that exceeded its timeout and clean up.

        Stops the whole process tree, removes the background-task registration
        and returns a definitive timeout ``ToolError`` carrying the partial
        output.  Long-running commands (servers/watchers/trailing ``&``) are
        NOT routed here — they keep running so the model can poll them with
        ``job_output``; this path is for ordinary commands whose subprocess
        would otherwise linger as a never-completing zombie task.
        """
        await process_task.stop()
        from kimix.tools.background.utils import remove_task_id
        remove_task_id(self._session, task_id)
        output = await _maybe_export_output_async(output)
        if output:
            message += "; partial output above"
        return ToolError(
            output=output,
            message=message,
            brief="Timeout",
        )

    async def _execute_background(self, params: PowershellParams) -> ToolReturnValue:
        """Execute a PowerShell command in background and return immediately with task_id."""
        cmd = params.command
        note = ""
        if cmd:
            # Same PowerShell-aware parser as the foreground path: repair
            # unclosed quotes/here-strings/comments and protect the try/catch
            # wrapper, reporting a warning instead of failing.
            fix = fix_pwsh_command(cmd)
            if fix is None:
                return ToolError(
                    output="",
                    message="Invalid PowerShell command.",
                    brief="Invalid PowerShell command",
                )
            if fix.changed:
                cmd = fix.command
                note = "\n[WARNING] " + fix.warning
        blocked = self._hardline_blocked(cmd)
        if blocked is not None:
            return blocked
        blocked = self._self_kill_blocked(cmd)
        if blocked is not None:
            return blocked
        self._resolve_pwsh()
        executable = self._pwsh_path if self._pwsh_path else (self._pwsh_fallback_path or "powershell")
        from kimix.tools.file.bash import shell_common

        raw_command = shell_common.wrap_pwsh_command(cmd)
        encoded_cmd, param_name, was_encoded = self._maybe_encode_command(raw_command)
        process_task = ProcessTask(
            executable,
            [*shell_common.PWSH_ONESHOT_FLAGS, param_name, encoded_cmd],
            None,
            _env_with_rg_bin_path(),
        )
        task_id = await process_task.start(self._session, "pwsh")
        if process_task.stream is not None:
            process_task.stream.format_output = functools.partial(
                self._format_background_output,
                cmd,
                params,
                rtk_rewritten=False,
                transform_warning=note,
            )

        return ToolOk(
            output=f"Running in background. task_id: `{task_id}`. Use `job_output` tool to retrieve output.",
            message=f"Command started in background. task_id: `{task_id}`" + note,
            brief="Background task started",
        )

    async def _continue_session(self, params: PowershellParams) -> ToolReturnValue:
        """Send input to an existing PowerShell session and optionally wait for output."""
        from kimix.tools.background.utils import get_all_tasks

        tasks = get_all_tasks(self._session)
        task_id = params.task_id.strip() if params.task_id else ""
        stream = tasks.get(task_id)
        if stream is None:
            started = [tid for tid, s in tasks.items() if await s.is_started()]
            if not started:
                return ToolError(
                    output="",
                    message=f"Task '{params.task_id}' not found. No running tasks.",
                    brief="Task not found",
                )
            return ToolError(
                output="",
                message=(
                    f"Task '{params.task_id}' not found. "
                    f"Available tasks: [{', '.join(started)}]"
                ),
                brief=f"Task '{params.task_id}' not found",
            )

        pattern = self._compile_pattern(params.wait_for_pattern)
        if isinstance(pattern, ToolError):
            return pattern

        await stream.pop_output()

        rtk_cmd, rtk_rewritten = _maybe_rewrite_shell_command_with_rtk(
            params.command, True, pwsh=True
        )
        input_text = rtk_cmd
        if not input_text.endswith("\n"):
            input_text += "\n"
        if not await stream.input(input_text):
            return ToolError(
                output="",
                message=f"Failed to send input to task '{task_id}'",
                brief="Send input failed",
            )

        from kimix.tools.background.utils import DEFAULT_INACTIVITY_TIMEOUT
        inactivity_timeout = min(DEFAULT_INACTIVITY_TIMEOUT, float(params.timeout))
        output, matched, elapsed = await stream.wait_for_output(
            timeout=params.timeout, pattern=pattern,
            inactivity_timeout=inactivity_timeout,
        )
        alive = await stream.thread_is_alive()
        status = "running" if alive else "completed"
        return await self._format_session_result(
            task_id, stream, params, output, status,
            wait_matched=matched, elapsed_seconds=elapsed,
            message=(f"[rtk] Data sent to `{task_id}`. Status: {status}." if rtk_rewritten else f"Data sent to `{task_id}`. Status: {status}."),
            brief="Data sent and output retrieved",
            rtk_rewritten=rtk_rewritten,
        )

    async def _process_output(
        self, command: str, params: PowershellParams, output: str, rtk_rewritten: bool = False
    ) -> tuple[str, str | None, bool, str | None]:
        """Summarize/export long output. Returns (display_output, path, truncated, original_path)."""
        # Secret redaction runs first (config-gated) so the dedup/export/
        # summarize pipeline never sees credentials.
        if self._redact_secrets and output:
            output = redact_sensitive_output(output)
        # When rtk itself folded the output, preserve the full stream so the
        # model can page through the unfiltered results.  This is done before
        # the local token filter so the raw rtk stream is captured even when
        # dedup/max_lines are disabled.
        # Dedup is always enabled (the ``deduplicate_output`` param was
        # removed), so the rtk full-stream save only applies to commands that
        # rtk itself rewrote — local dedup is skipped for those.
        rtk_original_path: str | None = None
        if output and rtk_rewritten and params.max_lines is None:
            rtk_original_path, _ = await _maybe_export_rtk_original_async(output)
        # Run token filter pipeline (dedup, truncate)
        output, original_path = await _token_filter_output(
            output,
            token_kill=True,
            max_lines=params.max_lines,
            rtk_rewritten=rtk_rewritten,
        )
        if original_path is None:
            original_path = rtk_original_path
        output_truncated = False
        if len(output) > 65536:
            # Preserve the full stream before replacing it with a summary: the
            # token filter may have left the output unchanged, so no original
            # has been saved yet and the summary would otherwise destroy it.
            original_path = await _save_original_output_async(output, original_path)
            output = await _summarize_long_output_async(self._session, command, output)
            output_truncated = True
        output = await _maybe_export_output_async(output)
        output_path = _extract_export_path(output)
        return output, output_path, output_truncated, original_path

    async def _format_session_result(
        self,
        task_id: str,
        stream: 'BackgroundStream' | None,
        params: PowershellParams,
        output: str,
        status: str,
        *,
        wait_matched: bool | None,
        elapsed_seconds: float | None,
        message: str,
        brief: str,
        rtk_rewritten: bool = False,
        exit_code_meaning: str | None = None,
        failure_hint: str | None = None,
    ) -> ToolReturnValue:
        """Build a ToolOk response with a structured output block."""
        processed, output_path, output_truncated, original_path = await self._process_output(
            params.command, params, output, rtk_rewritten=rtk_rewritten
        )
        if status != "completed":
            real_exit_code = None
        else:
            real_exit_code = stream.exit_code if stream else None
            if real_exit_code is None:
                real_exit_code = 0 if await stream.success() else None
        if exit_code_meaning is None and real_exit_code is not None:
            exit_code_meaning = interpret_exit_code(params.command, real_exit_code)
        block = _build_session_output_block(
            task_id=task_id,
            status=status,
            output=processed,
            exit_code=real_exit_code,
            exit_code_meaning=exit_code_meaning,
            failure_hint=failure_hint,
            wait_matched=wait_matched,
            elapsed_seconds=elapsed_seconds,
            output_path=output_path,
            output_truncated=output_truncated,
            original_path=original_path,
        )
        suffix = _original_saved_message(original_path)
        if suffix:
            message = f"{message} {suffix}" if message else suffix
        return ToolOk(output=block, message=message, brief=brief)

    async def _format_background_output(
        self,
        command: str,
        params: PowershellParams,
        output: str,
        success: bool,
        exit_code: int | None,
        elapsed_seconds: float | None,
        wait_matched: bool | None,
        *,
        rtk_rewritten: bool = False,
        transform_warning: str = "",
    ) -> tuple[str, str, str | None, str | None, bool]:
        """Format the output of a background/pwsh task for ``job_output``.

        Mirrors the foreground completion path so that messages about saved
        original output and saved command scripts are inherited when a task
        is retrieved via ``job_output``.

        Returns ``(processed_output, message, original_path, output_path,
        output_truncated)``.
        """
        processed, output_path, output_truncated, original_path = await self._process_output(
            command, params, output, rtk_rewritten=rtk_rewritten
        )
        suffix = _original_saved_message(original_path)
        expected = is_expected_exit(command, exit_code)
        if not success and not expected:
            hint = annotate_failure(output, command, exit_code)
            msg = "failed" + (f" Hint: {hint}" if hint else "")
            msg += transform_warning
            cmd_suffix = _command_saved_message(params.command, ".ps1", "PowerShell")
            if cmd_suffix:
                msg = f"{msg} {cmd_suffix}"
            if suffix:
                msg = f"{msg} {suffix}"
        else:
            if not success:
                msg = (interpret_exit_code(command, exit_code) or "expected non-zero exit") + transform_warning
            else:
                msg = "[rtk] success" if rtk_rewritten else "success"
                msg += transform_warning
            if suffix:
                msg = f"{msg} {suffix}"
        return processed, msg, original_path, output_path, output_truncated
