"""Auto-generated-file guard (plan 25, port of oh-my-pi auto-generated-guard.ts).

``write`` / ``edit`` / ``HashEdit`` refuse by default to modify files that
appear to be auto-generated.  Detection is deliberately **strict**:

1. Filename heuristics first (``zz_generated.*``, ``*.pb.go``, ``*_pb2.py``,
   ``*.gen.go|ts|js|py``, ``generated.*``, ``*.swagger.json``,
   ``*.openapi.json``, ``*.mock.*`` …).
2. Content check on the first :data:`CHECK_BYTE_COUNT` bytes /
   :data:`HEADER_LINE_LIMIT` header lines: extract the leading header comment
   block using per-extension comment styles (``//``, ``#``, ``--``,
   ``<!-- -->``; basename styles for Dockerfile/Makefile/Justfile), then match
   only strong markers (``@generated``, ``code generated by <name>``,
   ``this file was automatically generated``, and ``generated by`` + a known
   generator name).  Broad patterns like ``auto-generated`` are deliberately
   NOT used — they false-positive on hand-written files.

A tiny LRU (:data:`_MARKER_CACHE_MAX` entries) caches
``(mtime_ns, size) → marker`` per path so a rewritten file is re-scanned
instead of served stale.  Gated by the ``edit.block_auto_generated`` setting
(default ``True``); each tool also takes an ``allow_auto_generated`` param.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

import regex

from kimi_cli.session import Session
from kosong.tooling import ToolError

CHECK_BYTE_COUNT = 1024
HEADER_LINE_LIMIT = 40

KNOWN_GENERATOR_PATTERN = (
    r"(?:protoc(?:-gen-[\w-]+)?|sqlc|buf|swagger(?:-codegen)?|"
    r"openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|"
    r"deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|"
    r"informer-gen|kysely-codegen|napi-rs)"
)

# Strong markers only — deliberately strict (see oh-my-pi comment).
AUTO_GENERATED_HEADER_MARKERS: tuple[regex.Pattern[str], ...] = (
    regex.compile(r"@generated\b", regex.I),
    regex.compile(r"\bcode\s+generated\s+by\s+[a-z0-9_.-]+", regex.I),
    regex.compile(r"\bthis\s+file\s+was\s+automatically\s+generated\b", regex.I),
    regex.compile(rf"\bgenerated\s+by\s+{KNOWN_GENERATOR_PATTERN}\b", regex.I),
)

AUTO_GENERATED_FILENAME_PATTERNS: tuple[regex.Pattern[str], ...] = (
    regex.compile(r"^zz_generated\."),
    regex.compile(r"\.pb\.(?:go|cc|h|c|js|ts)$"),
    regex.compile(r"_pb2\.py$"),
    regex.compile(r"_pb2_grpc\.py$"),
    regex.compile(r"\.gen\.(?:go|ts|js|py)$"),
    regex.compile(r"^generated\.(?:go|ts|js|py)$"),
    regex.compile(r"\.swagger\.json$"),
    regex.compile(r"\.openapi\.json$"),
    regex.compile(r"\.mock\.(?:go|ts)$"),
    regex.compile(r"\.mocks?\.(?:go|ts|js)$"),
)

# Comment style ids: "slash" (// and /* */), "hash" (#), "sql" (--), "html" (<!-- -->)
_EXTENSION_COMMENT_STYLES: dict[str, tuple[str, ...]] = {
    ".py": ("hash",),
    ".rb": ("hash",),
    ".sh": ("hash",),
    ".bash": ("hash",),
    ".zsh": ("hash",),
    ".yml": ("hash",),
    ".yaml": ("hash",),
    ".toml": ("hash",),
    ".ini": ("hash",),
    ".cfg": ("hash",),
    ".conf": ("hash",),
    ".env": ("hash",),
    ".pl": ("hash",),
    ".r": ("hash",),
    ".c": ("slash",),
    ".cc": ("slash",),
    ".cpp": ("slash",),
    ".cs": ("slash",),
    ".dart": ("slash",),
    ".go": ("slash",),
    ".h": ("slash",),
    ".hpp": ("slash",),
    ".java": ("slash",),
    ".js": ("slash",),
    ".jsx": ("slash",),
    ".kt": ("slash",),
    ".kts": ("slash",),
    ".mjs": ("slash",),
    ".cjs": ("slash",),
    ".php": ("slash",),
    ".rs": ("slash",),
    ".scala": ("slash",),
    ".swift": ("slash",),
    ".ts": ("slash",),
    ".tsx": ("slash",),
    ".sql": ("sql",),
    ".html": ("html",),
    ".htm": ("html",),
    ".xml": ("html",),
    ".svg": ("html",),
    ".xhtml": ("html",),
}

_BASENAME_COMMENT_STYLES: dict[str, tuple[str, ...]] = {
    "dockerfile": ("hash",),
    "makefile": ("hash",),
    "justfile": ("hash",),
}


def strip_bom(content: str) -> str:
    """Remove a leading UTF-8 BOM if present."""
    if content.startswith("\ufeff"):
        return content[1:]
    return content


def get_comment_styles_for_path(file_path: str) -> tuple[str, ...]:
    """Return the comment style ids used to find a header comment in *file_path*."""
    name = Path(file_path).name.lower()
    styles = _BASENAME_COMMENT_STYLES.get(name)
    if styles is not None:
        return styles
    ext = Path(file_path).suffix.lower()
    return _EXTENSION_COMMENT_STYLES.get(ext, ("slash", "hash", "sql", "html"))


def is_auto_generated_file_name(file_path: str) -> bool:
    """True when the basename matches a known generated-file pattern."""
    name = Path(file_path).name
    return any(p.search(name) for p in AUTO_GENERATED_FILENAME_PATTERNS)


def extract_leading_header_comment_text(
    content: str, comment_styles: tuple[str, ...]
) -> str:
    """Collect the leading header comment block of *content*.

    Skips a shebang on line 0; then gathers contiguous comment lines (``//``,
    ``/* */`` multi-line blocks, ``#``, ``--``, ``<!-- -->`` blocks) up to
    :data:`HEADER_LINE_LIMIT` lines.  Blank lines are allowed once collection
    has started (header banners often span paragraphs); collection stops at
    the first non-comment, non-blank line.
    """
    content = strip_bom(content)
    lines = content.splitlines()
    collected: list[str] = []
    started = False
    in_block: str | None = None  # active multi-line opener: "slash" | "html"
    limit = min(len(lines), HEADER_LINE_LIMIT)

    for i in range(limit):
        line = lines[i]
        stripped = line.strip()

        # Shebang only allowed on the very first line.
        if i == 0 and stripped.startswith("#!"):
            continue

        if in_block is not None:
            collected.append(stripped)
            if in_block == "slash" and "*/" in stripped or in_block == "html" and "-->" in stripped:
                in_block = None
            started = True
            continue

        if not stripped:
            if started:
                collected.append("")
                continue
            # leading blanks before the header are fine to skip
            continue

        is_comment = False
        if "slash" in comment_styles:
            if stripped.startswith("//"):
                is_comment = True
            elif stripped.startswith("/*"):
                is_comment = True
                if "*/" not in stripped:
                    in_block = "slash"
        if not is_comment and "hash" in comment_styles and stripped.startswith("#"):
            is_comment = True
        if not is_comment and "sql" in comment_styles and stripped.startswith("--"):
            is_comment = True
        if not is_comment and "html" in comment_styles and stripped.startswith("<!--"):
            is_comment = True
            if "-->" not in stripped:
                in_block = "html"

        if is_comment:
            collected.append(stripped)
            started = True
        else:
            break

    return "\n".join(collected)


def detect_auto_generated_marker(content: str, file_path: str) -> str | None:
    """Return the detected marker string, or None when the file looks hand-written.

    Filename patterns win (the filename itself is reported as the marker);
    otherwise the header comment text is matched against the strong markers.
    """
    if is_auto_generated_file_name(file_path):
        return Path(file_path).name

    prefix = content[:CHECK_BYTE_COUNT]
    header = extract_leading_header_comment_text(
        prefix, get_comment_styles_for_path(file_path)
    )
    if not header:
        return None
    for pattern in AUTO_GENERATED_HEADER_MARKERS:
        match = pattern.search(header)
        if match is not None:
            return match.group(0).strip()
    return None


def build_auto_generated_error(display_path: str, detected: str) -> ToolError:
    """ToolError explaining the refusal (port of oh-my-pi's message)."""
    return ToolError(
        message=(
            f"Cannot modify auto-generated file: {display_path}\n\n"
            f'This file appears to be automatically generated (detected marker: "{detected}"). '
            "Changes will be overwritten the next time the code is regenerated. "
            "Edit the source (schema, template, or generator input) and regenerate instead, "
            "or pass allow_auto_generated=true to override."
        ),
        brief="Auto-generated file",
    )


def should_block_auto_generated(session: Session | None) -> bool:
    """Setting gate: ``edit.block_auto_generated`` (default True)."""
    if session is None:
        return True
    try:
        config = session.custom_config.get("config_json", {}).get("edit", {})
    except AttributeError:
        return True
    return bool(config.get("block_auto_generated", True))


# ── detection cache (port of the LRU(10) keyed by (mtime, size)) ─────────────

_MARKER_CACHE: OrderedDict[str, tuple[int, int, str | None]] = OrderedDict()
_MARKER_CACHE_MAX = 10


def _clear_marker_cache() -> None:
    """Test/debug hook: drop all cached markers."""
    _MARKER_CACHE.clear()


def _cached_marker(file_path: str) -> str | None:
    """Stat + cached content detection for *file_path* (missing file → None)."""
    path = Path(file_path)
    try:
        st = path.stat()
    except (FileNotFoundError, OSError):
        return None

    key = str(path)
    cached = _MARKER_CACHE.get(key)
    if cached is not None and cached[0] == st.st_mtime_ns and cached[1] == st.st_size:
        _MARKER_CACHE.move_to_end(key)
        return cached[2]

    try:
        raw = path.open("rb").read(CHECK_BYTE_COUNT * 4)
        text = raw.decode("utf-8", errors="replace")
    except (OSError, ValueError):
        text = ""

    marker = detect_auto_generated_marker(text, file_path)
    _MARKER_CACHE[key] = (st.st_mtime_ns, st.st_size, marker)
    _MARKER_CACHE.move_to_end(key)
    while len(_MARKER_CACHE) > _MARKER_CACHE_MAX:
        _MARKER_CACHE.popitem(last=False)
    return marker


# ── public API (used by tools) ────────────────────────────────────────────────


def _check_path_guard(
    absolute_path: str,
    display_path: str | None,
    session: Session | None,
) -> ToolError | None:
    """Return a refusal ToolError when *absolute_path* must not be edited."""
    if not should_block_auto_generated(session):
        return None
    if is_auto_generated_file_name(absolute_path):
        return build_auto_generated_error(
            display_path or absolute_path, Path(absolute_path).name
        )
    marker = _cached_marker(absolute_path)
    if marker is not None:
        return build_auto_generated_error(display_path or absolute_path, marker)
    return None


async def assert_editable_file(
    absolute_path: str,
    display_path: str | None = None,
    session: Session | None = None,
) -> ToolError | None:
    """Return a refusal ``ToolError`` when *absolute_path* looks auto-generated.

    Returns ``None`` when the file may be edited.  Best-effort stat/read:
    a missing file (new file) is always editable.
    """
    return _check_path_guard(absolute_path, display_path, session)


def assert_editable_file_content(
    content: str,
    display_path: str,
    session: Session | None = None,
) -> ToolError | None:
    """Content-based variant: return a refusal ``ToolError`` when generated.

    Uses ``display_path`` for the filename heuristics and extension styles.
    Returns ``None`` when the content may be written.
    """
    if not should_block_auto_generated(session):
        return None
    if is_auto_generated_file_name(display_path):
        return build_auto_generated_error(display_path, Path(display_path).name)
    marker = detect_auto_generated_marker(content, display_path)
    if marker is not None:
        return build_auto_generated_error(display_path, marker)
    return None
