import contextlib
from typing import Literal, override

import json_repair
from kaos.path import KaosPath
from kosong.tooling import CallableTool2, DisplayBlock, ToolError, ToolReturnValue, alias_note
from pydantic import AliasChoices, BaseModel, Field, field_validator

from kimi_cli import logger
from kimi_cli.session import Session
from kimi_cli.soul.agent import Runtime
from kimi_cli.soul.approval import Approval
from kimi_cli.tools.display import DiffDisplayBlock
from kimi_cli.tools.file import FileActions
from kimi_cli.tools.file.edit_safety import create_edit_parse_guard
from kimi_cli.tools.file.check_fmt import (
    check_json_text,
    check_toml_text,
    check_xml_text,
    check_yaml_text,
)
from kimi_cli.utils.diff import build_diff_blocks, format_unified_diff
from kimi_cli.utils.path import (
    is_within_directory,
    is_within_workspace,
    kaos_path_from_tool_input,
    kaos_path_from_user_input,
)
from kimi_cli.vfs import VFS

from .auto_generated import assert_editable_file
from .conflict_detect import (
    ConflictError,
    conflict_region_present,
    conflict_regions_equal,
    expand_content_tokens,
    find_dangling_openers,
    get_conflict_history,
    parse_bulk_directives,
    parse_conflict_uri,
    scan_conflict_lines,
    splice_conflict,
)
from .fs_cache import invalidate_fs_scan_after_write
from .snapshot_store import record_content_snapshot
from .utils import resolve_vfs

_BASE_DESCRIPTION = (
    "Create or fully replace a UTF-8 text file. Overwriting an existing "
    "auto-generated file (e.g. zz_generated.*, *.pb.go, *_pb2.py, *.gen.ts, "
    "or files with a '@generated' / 'Code generated by …' header) is refused "
    "by default; pass allow_auto_generated=True to override."
)

# Fuzzy mode map — maps common synonyms to canonical values
_MODE_MAP: dict[str, Literal["overwrite", "append"]] = {
    # overwrite synonyms
    "overwrite": "overwrite",
    "over_write": "overwrite",
    "over-write": "overwrite",
    "replace": "overwrite",
    "write": "overwrite",
    "create": "overwrite",
    "new": "overwrite",
    "truncate": "overwrite",
    "rewrite": "overwrite",
    "set": "overwrite",
    "put": "overwrite",
    # append synonyms
    "append": "append",
    "add": "append",
    "concat": "append",
    "concatenate": "append",
    "extend": "append",
    "attach": "append",
    "insert": "append",
    "prepend": "append",
    "after": "append",
}


class Params(BaseModel):
    model_config = {"populate_by_name": True}

    file_path: str = Field(
        validation_alias=AliasChoices("file_path", "path"),
        description="Path to write, resolved by the filesystem backend. "
        + alias_note("file_path", "path", word=False),
    )
    content: str = Field(
        validation_alias=AliasChoices("content", "text"),
        description="Full UTF-8 text content to write. "
        + alias_note("content", "text", word=False),
    )
    sandbox_permissions: Literal["workspace-write", "danger-full-access"] | None = Field(
        default=None,
        description=(
            "The wider sandbox mode this file operation needs "
            "(`workspace-write` or `danger-full-access`). Only valid as a "
            "one-shot retry of an operation the sandbox just denied; requires "
            "justification and user approval."
        ),
    )
    justification: str | None = Field(
        default=None,
        description=(
            "Required with sandbox_permissions: one sentence for the user "
            "explaining why this exact file operation needs the wider access."
        ),
    )
    mode: Literal["overwrite", "append"] = Field(
        description="Write mode: overwrite or append.",
        default="overwrite",
    )
    auto_fix_json: bool = Field(
        default=True,
        description="When True (default), attempt to repair broken JSON before writing. "
        "When False, fail with a format error if JSON is invalid.",
    )
    mkdir: bool = Field(
        default=True,
        description="When True (default), automatically create parent directories. "
        "When False, fail if the parent directory does not exist.",
    )
    show_diff: bool = Field(
        default=False,
        description="When True, include a unified diff in the tool output.",
    )
    allow_conflicts: bool = Field(
        default=False,
        description=(
            "When True, allow writing content that still contains conflict "
            "markers (opt-out of the conflict-marker write guard). Default "
            "False refuses to leave unresolved markers in a file."
        ),
    )
    allow_auto_generated: bool = Field(
        default=False,
        description=(
            "When True, allow overwriting files that appear to be "
            "auto-generated (opt-out of the auto-generated-file guard). "
            "Default False refuses to modify generated files."
        ),
    )

    @field_validator("mode", mode="before")
    @classmethod
    def _validate_mode(cls, v: str) -> str:
        normalized = v.strip().lower().replace("-", "_")
        canonical = _MODE_MAP.get(normalized)
        if canonical is None:
            raise ValueError(
                f"Invalid mode '{v}'. Must be 'overwrite' or 'append' (or a known synonym)."
            )
        return canonical


class WriteFile(CallableTool2[Params]):
    name: str = "write"
    description: str = _BASE_DESCRIPTION
    params: type[Params] = Params

    def __init__(self, runtime: Runtime, approval: Approval, session: Session, vfs: VFS | None = None):
        super().__init__()
        self._work_dir = runtime.builtin_args.KIMI_WORK_DIR
        self._additional_dirs = runtime.additional_dirs
        self._approval = approval
        self._session = session
        self._vfs = vfs
    async def _validate_path(
        self, path: KaosPath, raw_path: str
    ) -> tuple[ToolError | None, bool]:
        """Validate that the path is safe to write.

        Returns:
            A tuple of (error_or_none, is_inside_workspace).
        """
        resolved_path = path.canonical()
        original_is_absolute = kaos_path_from_user_input(raw_path).is_absolute()

        inside = is_within_workspace(
            resolved_path, self._work_dir, self._additional_dirs
        )
        if not inside and not original_is_absolute:
            return (
                ToolError(
                    message=(
                        f"`{raw_path}` is not an absolute path. "
                        "You must provide an absolute path to write a file "
                        "outside the working directory."
                    ),
                    brief="Invalid path",
                ),
                False,
            )

        protected_paths = self._session.custom_config.get("config_json", {}).get("protected_write_paths")
        if protected_paths:
            from .utils import check_path_protected
            if matched := check_path_protected(resolved_path, protected_paths, self._work_dir):
                return (
                    ToolError(
                        message=f"Writing to `{path}` is blocked by protected path rule: `{matched}`.",
                        brief="Protected path",
                    ),
                    False,
                )

        return None, inside

    @override
    async def __call__(self, params: Params) -> ToolReturnValue:
        display_path = params.file_path.replace("\\", "/")
        # The former `TODO: checks:` block here asked for a "path may contain secrets"
        # warning.  That check is deliberately NOT implemented in the write path: refusing or
        # annotating writes by filename heuristics would change tool-visible behaviour and
        # belongs to the secret-redaction subsystem, which already provides
        # `kimi_cli/utils/export.py::_looks_like_secret_filename` and the `soul/slash.py`
        # export warning.  Tracked as finding F-31 in reviews/tools/90-findings.md; the TODO
        # is removed so it cannot silently rot (FP-01).
        if not params.file_path:
            return ToolError(
                message="File path cannot be empty.",
                brief="Empty file path",
            )

        # Plan 24: conflict:// URIs resolve recorded marker blocks instead of
        # writing a path — dispatch before any KaosPath resolution.
        if "conflict://" in params.file_path:
            return await self._dispatch_conflict_write(params)

        try:
            p = kaos_path_from_tool_input(params.file_path, self._work_dir)
            logical_path = p
            display_logical_path = str(logical_path).replace("\\", "/")
            _outside = not is_within_directory(logical_path.canonical(), self._work_dir)
            err, path_is_inside = await self._validate_path(logical_path, params.file_path)
            if err:
                err.message = f"[out of work-dir] {err.message}" if _outside else err.message
                return err

            p = await resolve_vfs(params.file_path, self._vfs, for_write=True, work_dir=self._work_dir)
            display_p = str(p).replace("\\", "/")

            if await p.is_dir():
                return ToolError(
                    message=f"{'[out of work-dir] ' if _outside else ''}`{display_p}` is a directory, not a file.",
                    brief="Path is a directory",
                )

            # Create parent directories (or fail if mkdir=False)
            parent = p.parent
            if not await parent.exists():
                if params.mkdir:
                    try:
                        await parent.mkdir(parents=True, exist_ok=True)
                    except OSError as e:
                        return ToolError(
                            message=f"{'[out of work-dir] ' if _outside else ''}Failed to create parent directory for {display_p}: {e}",
                            brief="Parent directory not found",
                        )
                else:
                    return ToolError(
                        message=f"{'[out of work-dir] ' if _outside else ''}Parent directory does not exist: {parent}. Set mkdir=True to create it.",
                        brief="Directory not found",
                    )

            old_text = ""
            file_existed = False
            try:
                old_text = await p.read_text(encoding="utf-8", errors="strict")
                file_existed = True
            except FileNotFoundError:
                pass
            # Plan 25: auto-generated guard — refuse to modify files that
            # appear machine-generated (overwrite AND append) unless opted out.
            # Refusal happens before approval (no diff shown for refused writes).
            if file_existed and not params.allow_auto_generated:
                gen_err = await assert_editable_file(
                    str(p), display_path=display_p, session=self._session
                )
                if gen_err:
                    return gen_err
            # Plan 25: pre-overwrite safety snapshot — a mistaken overwrite
            # stays recoverable within the session via the snapshot store.
            if params.mode == "overwrite" and file_existed:
                with contextlib.suppress(Exception):
                    record_content_snapshot(
                        self._session, str(p), old_text, seen_lines=None
                    )

            new_text = params.content if params.mode == "overwrite" else old_text + params.content

            # In-memory format validation & fix (before any write)
            fmt_error = None
            file_path_str = str(logical_path)
            is_json = file_path_str.lower().endswith(".json")
            if is_json:
                fmt_error = check_json_text(new_text)
            elif file_path_str.lower().endswith((".yaml", ".yml")):
                fmt_error = check_yaml_text(new_text)
            elif file_path_str.lower().endswith(".toml"):
                fmt_error = check_toml_text(new_text)
            elif file_path_str.lower().endswith(".xml"):
                fmt_error = check_xml_text(new_text)

            # Try to repair broken JSON before building diff (if auto_fix_json is enabled)
            _repair_diff: str | None = None
            if is_json and fmt_error:
                if params.auto_fix_json:
                    try:
                        repaired_text = json_repair.repair_json(new_text, return_objects=False)
                        if repaired_text and repaired_text != new_text:
                            _repair_diff = format_unified_diff(
                                new_text, repaired_text, file_path_str
                            )
                            new_text = repaired_text
                            fmt_error = None
                    except Exception:
                        pass
                # else: auto_fix_json=False — leave fmt_error as-is, error reported below

            # Build diff blocks
            diff_blocks: list[DisplayBlock]
            if params.mode == "append" and file_existed:
                # Fast path: synthetic diff for append
                old_lines = old_text.splitlines()
                old_start = max(1, len(old_lines) - 2)
                old_context = "\n".join(old_lines[old_start - 1 :]) if old_lines else ""
                new_context = (
                    (old_context + "\n" if old_context else "") + params.content
                ).rstrip("\n")
                diff_blocks = [
                    DiffDisplayBlock(
                        path=file_path_str,
                        old_text=old_context,
                        new_text=new_context,
                        old_start=old_start,
                        new_start=old_start,
                    )
                ]
            else:
                diff_blocks = await build_diff_blocks(
                    file_path_str,
                    old_text,
                    new_text,
                )

            action = (
                FileActions.EDIT
                if path_is_inside
                else FileActions.EDIT_OUTSIDE
            )

            # Request approval
            approval_text = f"Write file `{display_logical_path}`"
            if params.justification:
                approval_text += f" — {params.justification}"
            result = await self._approval.request(
                self.name,
                action,
                approval_text,
                display=diff_blocks,
            )
            if not result:
                return result.rejection_error()

            # Write content to file (plan 24: mode-aware conflict guard).
            conflict_err, conflict_note, old_had_blocks = await self._conflict_guard(
                display_p,
                old_text,
                params.content,
                params.mode,
                file_existed=file_existed,
                allow_conflicts=params.allow_conflicts,
            )
            if conflict_err:
                return conflict_err
            # Plan 25: establish the FileMTime write baseline. mark_dirty
            # returns False when the file changed externally since the last
            # read (or was already written since) — the write proceeds
            # (it already passed approval) but the result gains a drift note
            # and the snapshot keeps the drift recoverable.
            _drift_note: str | None = None
            try:
                if not self._session.file_mtime.mark_dirty(params.file_path):
                    _drift_note = (
                        "Note: file changed since last read; snapshot recorded."
                    )
            except Exception:
                pass
            if params.mode == "append" and file_existed:
                await p.append_text(params.content, encoding="utf-8", errors="strict")
                expected_size = len(old_text.encode("utf-8")) + len(
                    params.content.encode("utf-8")
                )
            else:
                await p.write_text(new_text, encoding="utf-8", errors="strict")
                expected_size = len(new_text.encode("utf-8"))

            # Post-write size verification
            try:
                actual_size = (await p.stat()).st_size
            except Exception as e:
                logger.warning(
                    "write verification failed: {path}: {error}", path=params.file_path, error=e
                )
                return ToolError(
                    message=(
                        f"{'[out of work-dir] ' if _outside else ''}Write verification failed "
                        f"for {display_p}: {e}."
                    ),
                    brief="Verification failed",
                )
            if actual_size != expected_size:
                return ToolError(
                    message=(
                        f"{'[out of work-dir] ' if _outside else ''}Write verification failed "
                        "(size mismatch): "
                        f"expected {expected_size} bytes, got {actual_size} bytes. "
                        f"Path: {display_path}"
                    ),
                    brief="Verification failed",
                )

            # Compute file size in-memory
            file_size = expected_size
            # Plan 25: post-write snapshot (empty seen-lines: authoring
            # content is not knowing line numbers) + FS-cache invalidation.
            with contextlib.suppress(Exception):
                record_content_snapshot(
                    self._session, str(p), new_text, seen_lines=None
                )
            with contextlib.suppress(Exception):
                invalidate_fs_scan_after_write(str(p))
            action_desc = "overwritten" if params.mode == "overwrite" else "appended to"

            guard = create_edit_parse_guard(
                self._session,
                variant="write",
                arg=params.model_dump(),
                enabled_for_write=True,
            )
            await guard.observe_applied(str(logical_path), old_text, new_text)
            notes = await guard.finish()

            if fmt_error:
                msg = f"{'[out of work-dir] ' if _outside else ''}File successfully {action_desc}, but {fmt_error} Path: {display_path}"
                if notes:
                    msg += "\n\n" + "\n\n".join(notes)
                return ToolError(
                    message=msg,
                    brief="Format validation failed",
                )

            # Build result output
            result_parts: list[str] = []
            if params.show_diff:
                # Include diff in output if requested
                diff_text = format_unified_diff(old_text, new_text, file_path_str)
                if diff_text:
                    result_parts.append(f"Diff:\n{diff_text}\n")
            if _repair_diff:
                result_parts.append(f"JSON auto-repair diff:\n{_repair_diff}")

            result_output = "\n".join(result_parts)
            if result_output:
                result_output = result_output.rstrip("\n") + "\n"

            if (
                params.mode == "overwrite"
                and file_existed
                and old_had_blocks
                and not conflict_note
            ):
                # Clean overwrite of a conflicted file resolves every block in it.
                get_conflict_history(self._session).invalidate_path(str(p))

            message_parts = [
                f"{'[out of work-dir] ' if _outside else ''}File successfully {action_desc}. "
                f"Current size: {file_size} bytes. Path: {display_path}",
                " Verified: size matches.",
            ]
            if conflict_note:
                message_parts.append(conflict_note)
            if _drift_note:
                message_parts.append(f" {_drift_note}")
            if _repair_diff:
                message_parts.append(" JSON was auto-repaired.")
            if notes:
                message_parts.append("\n\n" + "\n\n".join(notes))

            return ToolReturnValue(
                is_error=False,
                output=result_output,
                message="".join(message_parts),
                display=[],
            )

        except Exception as e:
            logger.warning(
                "write failed: {path}: {error}", path=params.file_path, error=e
            )
            _outside_ex = False
            with contextlib.suppress(Exception):
                _outside_ex = not is_within_directory(
                    kaos_path_from_tool_input(params.file_path, self._work_dir).canonical(),
                    self._work_dir,
                )
            return ToolError(
                message=f"{'[out of work-dir] ' if _outside_ex else ''}Failed to write to {display_path}. Error: {e}.",
                brief="Failed to write file",
            )

    async def _conflict_guard(
        self,
        display_path: str,
        old_text: str,
        new_content: str,
        mode: str,
        *,
        file_existed: bool,
        allow_conflicts: bool,
    ) -> tuple[ToolError | None, str, bool]:
        """Mode-aware conflict-marker guard (plan 24).

        Returns ``(error_or_None, warning_note, old_had_blocks)``. Refuses
        unless ``allow_conflicts=True``:
        - overwrite: new content still holding marker blocks;
        - append: appended content with markers, or a file that ends inside
          an unclosed conflict block (dangling opener).
        """
        old_lines = old_text.replace("\r\n", "\n").splitlines() if old_text else []
        old_blocks = scan_conflict_lines(old_lines, 1)
        old_had_blocks = bool(old_blocks)
        new_lines = new_content.replace("\r\n", "\n").splitlines()
        new_blocks = scan_conflict_lines(new_lines, 1)

        if mode == "append" and file_existed:
            dangling = find_dangling_openers(old_lines)
            if dangling and not allow_conflicts:
                lines_str = "\n".join(
                    f"  line {n}: {text}" for n, text in dangling
                )
                return (
                    ToolError(
                        message=(
                            f"Conflict markers detected in `{display_path}`; refusing to append: "
                            "the file ends inside an unclosed conflict block.\n"
                            f"{lines_str}\n"
                            "Resolve the conflict first, or set allow_conflicts=True to append anyway."
                        ),
                        brief="Conflict markers detected",
                    ),
                    "",
                    old_had_blocks,
                )
            if new_blocks and not allow_conflicts:
                return (
                    self._conflict_markers_error(display_path, new_blocks),
                    "",
                    old_had_blocks,
                )
            note = ""
            if new_blocks:
                note = (
                    f" Warning: appended content still contains {len(new_blocks)} "
                    "unresolved conflict marker block(s) (allow_conflicts=True)."
                )
            elif old_had_blocks:
                note = (
                    f" Note: `{display_path}` still contains {len(old_blocks)} unresolved "
                    "conflict marker block(s); the appended text was clean. "
                    "Resolve them via `read <path>:conflicts` + `write({ path: \"conflict://<N>\", content })`."
                )
            return None, note, old_had_blocks

        # Overwrite mode (also covers brand-new files).
        if new_blocks and not allow_conflicts:
            return (
                self._conflict_markers_error(display_path, new_blocks),
                "",
                old_had_blocks,
            )
        note = ""
        if new_blocks:
            note = (
                f" Warning: written content still contains {len(new_blocks)} unresolved "
                "conflict marker block(s) (allow_conflicts=True)."
            )
        return None, note, old_had_blocks

    def _conflict_markers_error(
        self, display_path: str, blocks: list
    ) -> ToolError:
        found: list[tuple[int, str]] = []
        for block in blocks:
            found.append((block.start_line, "<<<<<<< marker block start"))
            found.append((block.end_line, ">>>>>>> marker block end"))
        lines_str = "\n".join(f"  line {n}: {text}" for n, text in found)
        return ToolError(
            message=(
                f"Conflict markers detected in `{display_path}`; refusing to write.\n"
                f"{lines_str}\n"
                f"The content still contains {len(blocks)} unresolved conflict marker block(s). "
                f"Resolve them first (e.g. read `{display_path}:conflicts`, then "
                '`write({ path: "conflict://<N>", content })`), or set allow_conflicts=True '
                "to write anyway."
            ),
            brief="Conflict markers detected",
        )

    async def _dispatch_conflict_write(self, params: Params) -> ToolReturnValue:
        """Route conflict://<N> / conflict://* writes (plan 24)."""
        try:
            parsed = parse_conflict_uri(params.file_path)
        except ConflictError as e:
            return ToolError(message=e.message, brief="Invalid conflict URI")
        if parsed is None:
            return ToolError(
                message=f"Invalid conflict write path: `{params.file_path}`.",
                brief="Invalid path",
            )
        if parsed.scope is not None:
            return ToolError(
                message=(
                    f"conflict://{parsed.id}/{parsed.scope} is read-only — "
                    f'write to `conflict://{parsed.id}` instead.'
                ),
                brief="Conflict scope is read-only",
            )
        if parsed.id == "*":
            return await self._resolve_all_conflicts(params.content)
        return await self._resolve_single_conflict_by_id(parsed.id, params.content)

    async def _resolve_single_conflict_by_id(
        self, conflict_id: int, content: str
    ) -> ToolReturnValue:
        history = get_conflict_history(self._session)
        entry = history.get(conflict_id)
        if entry is None:
            return ToolError(
                message=(
                    f"Conflict #{conflict_id} not found. Conflict ids are registered "
                    "when `read` surfaces a marker block; re-read the file to get a current id."
                ),
                brief="Conflict not found",
            )
        try:
            expanded = expand_content_tokens(content, entry)
        except ConflictError as e:
            return ToolError(message=e.message, brief="Token expansion failed")
        try:
            p = KaosPath(entry.absolute_path)
            original_text = await p.read_text(encoding="utf-8", errors="replace")
        except Exception as e:
            return ToolError(
                message=f"Cannot read {entry.display_path}: {e}",
                brief="Read failed",
            )
        try:
            splice = splice_conflict(original_text, entry, expanded)
        except ConflictError as e:
            return ToolError(message=e.message, brief="Conflict splice failed")
        try:
            await p.write_text(splice.text, encoding="utf-8")
        except Exception as e:
            return ToolError(
                message=f"Failed to write {entry.display_path}: {e}",
                brief="Write failed",
            )
        # Plan 25: conflict-resolution writes share the regular success path
        # hooks — post-write snapshot + FS-cache invalidation.
        with contextlib.suppress(Exception):
            record_content_snapshot(
                self._session, str(p), splice.text, seen_lines=None
            )
        with contextlib.suppress(Exception):
            invalidate_fs_scan_after_write(str(p))
          # Invalidate the resolved entry and stale duplicate registrations.
        history.invalidate(entry.id)
        for other in list(history.entries()):
            if (
                other.absolute_path == entry.absolute_path
                and other.id != entry.id
                and conflict_regions_equal(other, entry)
                and not conflict_region_present(splice.text, other)
            ):
                history.invalidate(other.id)
        self._session.file_mtime.clean_file(entry.absolute_path)

        message = (
            f"Resolved conflict #{conflict_id} at line(s) L{entry.start_line}-"
            f"{entry.end_line} in {entry.display_path}."
        )
        trimmed = splice.trimmed_leading + splice.trimmed_trailing
        if trimmed:
            message += (
                f" Note: dropped {trimmed} content line(s) that duplicated the code "
                "adjacent to the conflict region (boundary-echo repair)."
            )
        return ToolReturnValue(
            is_error=False,
            output="",
            message=message,
            display=[],
        )

    async def _resolve_all_conflicts(self, content: str) -> ToolReturnValue:
        history = get_conflict_history(self._session)
        all_entries = history.entries()
        if not all_entries:
            return ToolError(
                message=(
                    "conflict:// has nothing to resolve — no conflicts are currently "
                    "registered. Re-read the file(s) with conflicts first."
                ),
                brief="No conflicts registered",
            )

        directives = parse_bulk_directives(content)
        if directives is not None:
            unknown = sorted(set(directives) - {e.id for e in all_entries})
            if unknown:
                return ToolError(
                    message=(
                        "Unknown conflict id(s) in bulk directives: "
                        f"{', '.join(f'#{i}' for i in unknown)}. "
                        "Re-read the file(s) to get current ids."
                    ),
                    brief="Unknown conflict ids",
                )
            targets = [e for e in all_entries if e.id in directives]
        else:
            targets = list(all_entries)

        # Group by file; splice bottom-up so earlier anchors stay valid.
        by_path: dict[str, list] = {}
        for entry in targets:
            by_path.setdefault(entry.absolute_path, []).append(entry)

        resolved_ids: list[int] = []
        failures: list[str] = []
        remaining: list[int] = []
        for absolute_path, file_entries in by_path.items():
            file_entries.sort(key=lambda e: e.start_line, reverse=True)
            try:
                p = KaosPath(absolute_path)
                text = await p.read_text(encoding="utf-8", errors="replace")
                for entry in file_entries:
                    side = directives.get(entry.id) if directives else None
                    block_content = (
                        f"@{side}" if directives and side else content
                    )
                    expanded = expand_content_tokens(block_content, entry)
                    splice = splice_conflict(text, entry, expanded)
                    text = splice.text
                    resolved_ids.append(entry.id)
                await p.write_text(text, encoding="utf-8")
                self._session.file_mtime.clean_file(absolute_path)
                # Plan 25: same hooks as the regular write success path.
                with contextlib.suppress(Exception):
                    record_content_snapshot(
                        self._session, absolute_path, text, seen_lines=None
                    )
                with contextlib.suppress(Exception):
                    invalidate_fs_scan_after_write(absolute_path)
            except ConflictError as e:
                failures.append(f"{absolute_path}: {e.message}")
                resolved_ids = [
                    rid for rid in resolved_ids if rid not in {x.id for x in file_entries}
                ]
                remaining.extend(entry.id for entry in file_entries)
            except Exception as e:
                failures.append(f"{absolute_path}: {e}")
                resolved_ids = [
                    rid for rid in resolved_ids if rid not in {x.id for x in file_entries}
                ]
                remaining.extend(entry.id for entry in file_entries)

        for rid in resolved_ids:
            history.invalidate(rid)
        # Drop stale duplicate registrations of just-resolved blocks: same file,
        # identical region, and that region no longer present on disk.
        try:
            disk_texts: dict[str, str] = {}
            for absolute_path in by_path:
                disk_texts[absolute_path] = await KaosPath(absolute_path).read_text(
                    encoding="utf-8", errors="replace"
                )
            for entry in list(history.entries()):
                disk = disk_texts.get(entry.absolute_path)
                if disk is None or entry.id in remaining:
                    continue
                resolved_here = [
                    e for e in targets
                    if e.absolute_path == entry.absolute_path
                ]
                if any(
                    conflict_regions_equal(entry, e)
                    and not conflict_region_present(disk, entry)
                    for e in resolved_here
                ):
                    history.invalidate(entry.id)
        except Exception:
            pass  # best-effort cleanup only

        if failures:
            message = (
                f"Bulk resolve finished with errors: resolved {len(resolved_ids)} conflict(s), "
                f"{len(failures)} file(s) failed (all-or-nothing per file)."
            )
            for failure in failures:
                message += f"\n- {failure}"
            if remaining:
                message += (
                    f" Remaining conflict ids: {', '.join(f'#{i}' for i in sorted(remaining))}."
                )
            return ToolReturnValue(
                is_error=True,
                output="",
                message=message,
                display=[],
            )
        message = (
            f"Resolved {len(resolved_ids)} conflict(s) across {len(by_path)} file(s): "
            f"{', '.join(f'#{i}' for i in sorted(resolved_ids))}."
        )
        leftover = [e.id for e in history.entries()]
        if leftover:
            message += (
                f" Still registered: {', '.join(f'#{i}' for i in sorted(leftover))}."
            )
        return ToolReturnValue(
            is_error=False,
            output="",
            message=message,
            display=[],
        )
