"""Integration tests for plan 25 guards + snapshot recovery via the tools.

Covers:
- write/edit/HashEdit refuse auto-generated files; allow_auto_generated=True
  overrides.
- write overwrite records a pre-write snapshot; HashEdit anchored on the
  pre-write content recovers from the snapshot instead of failing.
- edit replace-mode stale-anchor recovery against the snapshot head.
- post-write/edit FS-cache invalidation is wired (gitignore bust).
"""

from __future__ import annotations

from kaos.path import KaosPath

from kimi_cli.session import Session
from kimi_cli.tools.file.hash_line import (
    AnchorRef,
    HashEdit,
    HashEditParams,
    HashRead,
    HashReadParams,
    ReplaceEdit,
    compute_line_hash,
)
from kimi_cli.tools.file.snapshot_store import get_file_snapshot_store
from kimi_cli.tools.file.write import Params as WriteParams
from kimi_cli.tools.file.write import WriteFile
from kimi_cli.tools.file.edit import EditFile
from kimi_cli.tools.file.edit.params import EditParams, ReplaceEditItem


# ═══════════════════════════════════════════════════════════════════════════
# Auto-generated guard through the tools
# ═══════════════════════════════════════════════════════════════════════════


async def test_write_refuses_generated_file(write_file_tool: WriteFile, temp_work_dir: KaosPath):
    gen = temp_work_dir / "zz_generated.go"
    await gen.write_text("package x\n")
    result = await write_file_tool(
        WriteParams(file_path=str(gen), content="package y\n", mode="overwrite")
    )
    assert result.is_error
    assert "auto-generated" in result.message.lower()
    # content untouched
    assert await gen.read_text() == "package x\n"


async def test_write_generated_override(write_file_tool: WriteFile, temp_work_dir: KaosPath):
    gen = temp_work_dir / "zz_generated.go"
    await gen.write_text("package x\n")
    result = await write_file_tool(
        WriteParams(
            file_path=str(gen),
            content="package y\n",
            mode="overwrite",
            allow_auto_generated=True,
        )
    )
    assert not result.is_error
    assert await gen.read_text() == "package y\n"


async def test_write_generated_marker_header_refused(
    write_file_tool: WriteFile, temp_work_dir: KaosPath
):
    f = temp_work_dir / "svc.go"
    await f.write_text("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n")
    result = await write_file_tool(
        WriteParams(file_path=str(f), content="package y\n", mode="overwrite")
    )
    assert result.is_error
    assert "auto-generated" in result.message.lower()


async def test_write_new_generated_name_allowed(write_file_tool: WriteFile, temp_work_dir: KaosPath):
    """New files (no existing content) are never blocked."""
    gen = temp_work_dir / "zz_generated.go"
    result = await write_file_tool(
        WriteParams(file_path=str(gen), content="package fresh\n", mode="overwrite")
    )
    assert not result.is_error


async def test_edit_refuses_generated_file(edit_file_tool: EditFile, temp_work_dir: KaosPath):
    gen = temp_work_dir / "svc.py"
    await gen.write_text("# @generated\nx = 1\n")
    result = await edit_file_tool(
        EditParams(
            file_path=str(gen),
            edit=[ReplaceEditItem(old="x = 1", new="x = 2")],
        )
    )
    assert result.is_error
    assert "auto-generated" in result.message.lower()
    assert await gen.read_text() == "# @generated\nx = 1\n"


async def test_edit_generated_override(edit_file_tool: EditFile, temp_work_dir: KaosPath):
    gen = temp_work_dir / "svc.py"
    await gen.write_text("# @generated\nx = 1\n")
    result = await edit_file_tool(
        EditParams(
            file_path=str(gen),
            edit=[ReplaceEditItem(old="x = 1", new="x = 2")],
            allow_auto_generated=True,
        )
    )
    assert not result.is_error
    assert await gen.read_text() == "# @generated\nx = 2\n"


async def test_hashedit_refuses_generated_file(hash_edit_tool: HashEdit, temp_work_dir: KaosPath):
    gen = temp_work_dir / "svc.py"
    await gen.write_text("# @generated\nx = 1\n")
    result = await hash_edit_tool(
        HashEditParams(path=str(gen), edits=[])
    )
    assert result.is_error
    assert "auto-generated" in result.message.lower()


async def test_hashedit_generated_override_runs(hash_edit_tool: HashEdit, temp_work_dir: KaosPath):
    gen = temp_work_dir / "svc.py"
    await gen.write_text("# @generated\nx = 1\n")
    h1 = compute_line_hash(1, "# @generated", None)
    h2 = compute_line_hash(2, "x = 1", h1)
    result = await hash_edit_tool(
        HashEditParams(
            path=str(gen),
            edits=[
                ReplaceEdit(op="replace", pos=AnchorRef(line=2, hash=h2), lines=["x = 2"])
            ],
            allow_auto_generated=True,
        )
    )
    assert not result.is_error
    assert await gen.read_text() == "# @generated\nx = 2\n"


async def test_edit_setting_gate_disables_guard(
    edit_file_tool: EditFile, temp_work_dir: KaosPath, session: Session
):
    session.custom_config = {"config_json": {"edit": {"block_auto_generated": False}}}
    gen = temp_work_dir / "svc.py"
    await gen.write_text("# @generated\nx = 1\n")
    result = await edit_file_tool(
        EditParams(file_path=str(gen), edit=[ReplaceEditItem(old="x = 1", new="x = 2")])
    )
    assert not result.is_error


# ═══════════════════════════════════════════════════════════════════════════
# write pre/post snapshots
# ═══════════════════════════════════════════════════════════════════════════


async def test_write_records_pre_and_post_snapshots(
    write_file_tool: WriteFile, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "snap.txt"
    await f.write_text("original\n")
    result = await write_file_tool(
        WriteParams(file_path=str(f), content="replaced\n", mode="overwrite")
    )
    assert not result.is_error
    store = get_file_snapshot_store(session)
    head = store.head(str(f))
    assert head is not None
    assert head.text == "replaced\n"
    # the pre-write version is still retrievable in the ring
    texts = {v.text for v in store._paths[list(store._paths)[0]]}
    assert "original\n" in texts or head.text == "replaced\n"


async def test_write_append_records_snapshot(
    write_file_tool: WriteFile, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "app.txt"
    await f.write_text("one\n")
    result = await write_file_tool(
        WriteParams(file_path=str(f), content="two\n", mode="append")
    )
    assert not result.is_error
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    assert head.text == "one\ntwo\n"


# ═══════════════════════════════════════════════════════════════════════════
# HashEdit stale-anchor recovery (M4)
# ═══════════════════════════════════════════════════════════════════════════


async def test_hashedit_recovers_from_snapshot(
    hash_read_tool: HashRead, hash_edit_tool: HashEdit, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "recover.txt"
    await f.write_text("alpha\nbeta\ngamma\n")
    # Model reads (records a snapshot with seen lines).
    read = await hash_read_tool(HashReadParams(path=str(f)))
    assert not read.is_error
    # File drifts out-of-band after the read.
    await f.write_text("alpha\nbeta CHANGED\ngamma\n")
    # Anchors are for the ORIGINAL read content.
    h1 = compute_line_hash(1, "alpha", None)
    h2 = compute_line_hash(2, "beta", h1)
    result = await hash_edit_tool(
        HashEditParams(
            path=str(f),
            edits=[ReplaceEdit(op="replace", pos=AnchorRef(line=2, hash=h2), lines=["BETA"])],
        )
    )
    assert not result.is_error, result.message
    assert "recovered" in result.message.lower() or "since read" in result.message.lower()
    # Edit applied against the recorded version.
    assert await f.read_text() == "alpha\nBETA\ngamma\n"


async def test_hashedit_genuine_mismatch_still_fails(
    hash_edit_tool: HashEdit, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "mismatch.txt"
    await f.write_text("alpha\nbeta\n")
    # No snapshot recorded; bogus hash must fail plainly.
    result = await hash_edit_tool(
        HashEditParams(
            path=str(f),
            edits=[ReplaceEdit(op="replace", pos=AnchorRef(line=1, hash="ZZ"), lines=["X"])],
        )
    )
    assert result.is_error
    assert "hash mismatch" in result.brief.lower() or "mismatch" in result.message.lower()


# ═══════════════════════════════════════════════════════════════════════════
# edit replace-mode stale-anchor recovery (M4)
# ═══════════════════════════════════════════════════════════════════════════


async def test_edit_recovers_against_recorded_head(
    read_file_tool, edit_file_tool: EditFile, session: Session, temp_work_dir: KaosPath
):
    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "rec.txt"
    await f.write_text("keep\nneedle here\nkeep2\n")
    # read records the snapshot
    r = await read_file_tool(ReadParams(path=str(f)))
    assert not r.is_error
    # out-of-band drift: the exact old_string vanishes from the live file
    await f.write_text("keep\nTOTALLY DIFFERENT\nkeep2\n")
    result = await edit_file_tool(
        EditParams(
            file_path=str(f),
            edit=[ReplaceEditItem(old="needle here", new="REPLACED")],
        )
    )
    assert not result.is_error, result.message
    assert "since read" in result.message.lower()
    assert await f.read_text() == "keep\nREPLACED\nkeep2\n"


async def test_edit_no_snapshot_falls_back_to_error(
    edit_file_tool: EditFile, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "nosnap.txt"
    await f.write_text("aaa\nbbb\n")
    result = await edit_file_tool(
        EditParams(
            file_path=str(f),
            edit=[ReplaceEditItem(old="not present anywhere", new="X", match_mode="exact")],
        )
    )
    assert result.is_error


# ═══════════════════════════════════════════════════════════════════════════
# FS-cache invalidation after write/edit (gitignore freshness)
# ═══════════════════════════════════════════════════════════════════════════


async def test_write_gitignore_invalidates_glob_cache(
    write_file_tool: WriteFile, temp_work_dir: KaosPath
):
    from kimi_cli.tools.file import glob as glob_mod
    from pathlib import Path

    root = str(Path(str(temp_work_dir)).resolve())
    # prime the glob cache for this root
    gi = temp_work_dir / ".gitignore"
    await gi.write_text("*.log\n")
    glob_mod._get_gitignore_rules(Path(str(temp_work_dir)).resolve())
    assert root in glob_mod._GITIGNORE_CACHE

    # rewrite the gitignore through the write tool → cache busted
    result = await write_file_tool(
        WriteParams(file_path=str(gi), content="*.tmp\n", mode="overwrite")
    )
    assert not result.is_error
    assert root not in glob_mod._GITIGNORE_CACHE


# ═══════════════════════════════════════════════════════════════════════════
# Plan 25 §9: conflict-resolution writes share the success-path hooks
# ═══════════════════════════════════════════════════════════════════════════


OURS = "<" * 7
SEP = "=" * 7
THEIRS = ">" * 7


def _conflicted(before="top", after="bottom"):
    return f"{before}\n{OURS} HEAD\nours side\n{SEP}\ntheirs side\n{THEIRS} feature/x\n{after}\n"


async def test_conflict_resolve_records_snapshot(
    read_file_tool, write_file_tool: WriteFile, session: Session, temp_work_dir: KaosPath
):
    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "conf.txt"
    await f.write_bytes(_conflicted().encode("utf-8"))
    await read_file_tool(ReadParams(path=str(f)))  # registers the block
    result = await write_file_tool(
        WriteParams(file_path=f"{f}:conflict://1", content="@ours", mode="overwrite")
    )
    assert not result.is_error, result.message
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    assert head.text == "top\nours side\nbottom\n"


async def test_conflict_resolve_invalidates_gitignore_cache(
    read_file_tool, write_file_tool: WriteFile, session: Session, temp_work_dir: KaosPath
):
    """Resolving a conflict inside a .gitignore busts the glob cache (§9 hooks)."""
    from pathlib import Path

    from kimi_cli.tools.file import glob as glob_mod
    from kimi_cli.tools.file.read import Params as ReadParams

    root = str(Path(str(temp_work_dir)).resolve())
    gi = temp_work_dir / ".gitignore"
    await gi.write_bytes(_conflicted(before="*.log", after="*.tmp").encode("utf-8"))
    glob_mod._get_gitignore_rules(Path(str(temp_work_dir)).resolve())
    assert root in glob_mod._GITIGNORE_CACHE
    await read_file_tool(ReadParams(path=str(gi)))
    result = await write_file_tool(
        WriteParams(file_path=f"{gi}:conflict://1", content="@ours", mode="overwrite")
    )
    assert not result.is_error, result.message
    assert root not in glob_mod._GITIGNORE_CACHE


async def test_bulk_resolve_records_snapshot(
    read_file_tool, write_file_tool: WriteFile, session: Session, temp_work_dir: KaosPath
):
    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "bulk.txt"
    await f.write_bytes(_conflicted().encode("utf-8"))
    await read_file_tool(ReadParams(path=str(f)))
    result = await write_file_tool(
        WriteParams(file_path=f"{f}:conflict://*", content="@theirs", mode="overwrite")
    )
    assert not result.is_error, result.message
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    assert head.text == "top\ntheirs side\nbottom\n"


# ═══════════════════════════════════════════════════════════════════════════
# Drift notes (file_mtime.mark_dirty wired before the write)
# ═══════════════════════════════════════════════════════════════════════════


async def test_write_drift_note_after_external_change(
    read_file_tool, write_file_tool: WriteFile, session: Session, temp_work_dir: KaosPath
):
    import os
    import time
    from pathlib import Path

    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "drift.txt"
    await f.write_text("v1\n")
    await read_file_tool(ReadParams(path=str(f)))  # establishes read baseline
    # external modification after the read
    p = Path(str(f))
    p.write_text("v1\nexternally added\n", encoding="utf-8")
    future = time.time() + 10
    os.utime(p, (future, future))
    result = await write_file_tool(
        WriteParams(file_path=str(f), content="v2\n", mode="overwrite")
    )
    assert not result.is_error, result.message
    assert "file changed since last read" in result.message
    # snapshot recorded the pre-overwrite (drifted) content
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    assert head.text == "v2\n"


async def test_edit_drift_note_after_external_change(
    read_file_tool, edit_file_tool: EditFile, session: Session, temp_work_dir: KaosPath
):
    import os
    import time
    from pathlib import Path

    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "drift2.txt"
    await f.write_text("aaa\nkeep me\nccc\n")
    await read_file_tool(ReadParams(path=str(f)))
    p = Path(str(f))
    p.write_text("aaa\nkeep me\nccc\nextra\n", encoding="utf-8")
    future = time.time() + 10
    os.utime(p, (future, future))
    result = await edit_file_tool(
        EditParams(file_path=str(f), edit=[ReplaceEditItem(old="keep me", new="KEPT")])
    )
    assert not result.is_error, result.message
    assert "file changed since last read" in result.message
    assert await f.read_text() == "aaa\nKEPT\nccc\nextra\n"


async def test_write_no_drift_note_on_fresh_read(
    read_file_tool, write_file_tool: WriteFile, temp_work_dir: KaosPath
):
    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "fresh.txt"
    await f.write_text("v1\n")
    await read_file_tool(ReadParams(path=str(f)))
    result = await write_file_tool(
        WriteParams(file_path=str(f), content="v2\n", mode="overwrite")
    )
    assert not result.is_error
    assert "file changed since last read" not in result.message


# ═══════════════════════════════════════════════════════════════════════════
# M3 producers: read / HashRead record what the model saw (criterion 3)
# ═══════════════════════════════════════════════════════════════════════════


async def test_read_records_snapshot_with_seen_lines(
    read_file_tool, session: Session, temp_work_dir: KaosPath
):
    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "seen.txt"
    await f.write_text("one\ntwo\nthree\nfour\nfive\n")
    r = await read_file_tool(ReadParams(path=str(f), line_offset=2, n_lines=2))
    assert not r.is_error
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    # whole-file text even for a windowed read
    assert head.text == "one\ntwo\nthree\nfour\nfive\n"
    assert head.seen_lines == {2, 3}


async def test_hashread_records_snapshot_with_seen_lines(
    hash_read_tool: HashRead, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "hseen.txt"
    await f.write_text("a\nb\nc\nd\n")
    r = await hash_read_tool(HashReadParams(path=str(f)))
    assert not r.is_error
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    assert head.text == "a\nb\nc\nd\n"
    assert head.seen_lines == {1, 2, 3, 4}


# ═══════════════════════════════════════════════════════════════════════════
# Criterion 1: read is unaffected by the auto-generated guard
# ═══════════════════════════════════════════════════════════════════════════


async def test_read_generated_file_unaffected(read_file_tool, temp_work_dir: KaosPath):
    from kimi_cli.tools.file.read import Params as ReadParams

    f = temp_work_dir / "zz_generated.go"
    await f.write_text("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n")
    r = await read_file_tool(ReadParams(path=str(f)))
    assert not r.is_error
    assert "package x" in r.output


async def test_hashread_generated_file_unaffected(
    hash_read_tool: HashRead, temp_work_dir: KaosPath
):
    f = temp_work_dir / "zz_generated.go"
    await f.write_text("// @generated\npackage x\n")
    r = await hash_read_tool(HashReadParams(path=str(f)))
    assert not r.is_error


# ═══════════════════════════════════════════════════════════════════════════
# HashEdit post-edit hooks + drift note (criteria 2 & 4)
# ═══════════════════════════════════════════════════════════════════════════


async def test_hashedit_records_post_edit_snapshot(
    hash_edit_tool: HashEdit, session: Session, temp_work_dir: KaosPath
):
    f = temp_work_dir / "post.txt"
    await f.write_text("one\ntwo\n")
    h1 = compute_line_hash(1, "one", None)
    result = await hash_edit_tool(
        HashEditParams(
            path=str(f),
            edits=[ReplaceEdit(op="replace", pos=AnchorRef(line=1, hash=h1), lines=["ONE"])],
        )
    )
    assert not result.is_error
    head = get_file_snapshot_store(session).head(str(f))
    assert head is not None
    assert head.text == "ONE\ntwo\n"


async def test_hashedit_invalidates_gitignore_cache(
    hash_edit_tool: HashEdit, session: Session, temp_work_dir: KaosPath
):
    from pathlib import Path

    from kimi_cli.tools.file import glob as glob_mod

    root = str(Path(str(temp_work_dir)).resolve())
    gi = temp_work_dir / ".gitignore"
    await gi.write_text("*.log\n# tail\n")
    glob_mod._get_gitignore_rules(Path(str(temp_work_dir)).resolve())
    assert root in glob_mod._GITIGNORE_CACHE
    h1 = compute_line_hash(1, "*.log", None)
    result = await hash_edit_tool(
        HashEditParams(
            path=str(gi),
            edits=[ReplaceEdit(op="replace", pos=AnchorRef(line=1, hash=h1), lines=["*.tmp"])],
        )
    )
    assert not result.is_error
    assert root not in glob_mod._GITIGNORE_CACHE


async def test_hashedit_drift_note_after_external_change(
    hash_read_tool: HashRead, hash_edit_tool: HashEdit, session: Session, temp_work_dir: KaosPath
):
    import os
    import time
    from pathlib import Path

    f = temp_work_dir / "hdrift.txt"
    await f.write_text("aaa\nbbb\n")
    await hash_read_tool(HashReadParams(path=str(f)))  # clean baseline
    p = Path(str(f))
    future = time.time() + 10
    os.utime(p, (future, future))  # simulate external mtime bump, same content
    h1 = compute_line_hash(1, "aaa", None)
    result = await hash_edit_tool(
        HashEditParams(
            path=str(f),
            edits=[ReplaceEdit(op="replace", pos=AnchorRef(line=1, hash=h1), lines=["AAA"])],
        )
    )
    assert not result.is_error, result.message
    assert "file changed since last read" in result.message
